ALTER TABLE SD.USER_ROLE 
DROP CONSTRAINT EMPLOYEE_ROLE_EMPLOYEES_FK;

ALTER TABLE SD.USER_ROLE 
DROP CONSTRAINT EMPLOYEE_ROLE_ROLES_FK1;

ALTER TABLE SD.USERS 
DROP CONSTRAINT USERS_EMPLOYEES_FK1;

ALTER TABLE SD.ROLE_PRIVILEGE 
DROP CONSTRAINT ROLE_PRIVILEGE_PRIVILEGE__FK1;

ALTER TABLE SD.ROLE_PRIVILEGE 
DROP CONSTRAINT ROLE_PRIVILEGE_ROLES_FK1;

ALTER TABLE SD.SUPPORTING_SERVICES 
DROP CONSTRAINT SUPPORTING_SERVICES_SERVI_FK1;

ALTER TABLE SD.SUPPORTING_SERVICES 
DROP CONSTRAINT SUPPORTING_SERVICES_SERVI_FK2;

ALTER TABLE SD.SOLUTIONS 
DROP CONSTRAINT PROBLEM_SOLUTIONS_PROBLEM_FK1;

ALTER TABLE SD.SOLUTIONS 
DROP CONSTRAINT PROBLEM_SOLUTIONS_SOLUTIO_FK1;

ALTER TABLE SD.SOLUTIONS 
DROP CONSTRAINT SOLUTIONS_EMPLOYEES_FK;

ALTER TABLE SD.SOLUTIONS 
DROP CONSTRAINT SOLUTIONS_SOLUTION_TYPES_FK;

ALTER TABLE SD.SIGNAL_TYPES 
DROP CONSTRAINT SIGNAL_TYPES_SIGNAL_OBJEC_FK1;

ALTER TABLE SD.SIGNAL_TYPES 
DROP CONSTRAINT SIGNAL_TYPES_SIGNAL_SIGNI_FK;

ALTER TABLE SD.SIGNAL_OBJECT_ATTRIBUTE_TYPES 
DROP CONSTRAINT SIGNAL_OBJECT_ATTRIBUTE_TYP_FK;

ALTER TABLE SD.SIGNAL_GENERATORS 
DROP CONSTRAINT SIGNAL_GENERATORS_RECEIVER_FK;

ALTER TABLE SD.SIGNAL_GENERATORS 
DROP CONSTRAINT SIGNAL_GENERATORS_SIGNAL_FK;

ALTER TABLE SD.SIGNAL_ATTRIBUTES 
DROP CONSTRAINT SIGNAL_ATTRIBUTES_SIGNAL__FK1;

ALTER TABLE SD.SIGNAL_ATTRIBUTES 
DROP CONSTRAINT SIGNAL_PARAMS_SIGNALS_FK;

ALTER TABLE SD.SERVICE_MANAGERS 
DROP CONSTRAINT SERVICE_MANAGERS_EMPLOYEE_FK1;

ALTER TABLE SD.SERVICE_MANAGERS 
DROP CONSTRAINT SERVICE_MANAGERS_SERVICES_FK;

ALTER TABLE SD.SERVICES 
DROP CONSTRAINT SERVICES_SERVICE_TYPES_FK;

ALTER TABLE SD.SERVICES 
DROP CONSTRAINT SERVICES_SLA_FK;

ALTER TABLE SD.REQUEST_ATTRIBUTE_TYPES 
DROP CONSTRAINT REQUEST_ATTRIBUTE_TYPES_C_FK1;

ALTER TABLE SD.REQUEST_ATTRIBUTES 
DROP CONSTRAINT REQUEST_ATTRIBUTES_REQUES_FK1;

ALTER TABLE SD.REQUEST_ATTRIBUTES 
DROP CONSTRAINT REQ_ATT_REQ_FK;

ALTER TABLE SD.REQUESTS 
DROP CONSTRAINT REQUESTS_CATEGORIES_RF_FK;

ALTER TABLE SD.REQUESTS 
DROP CONSTRAINT REQUESTS_EMPLOYEES_FK;

ALTER TABLE SD.REQUESTS 
DROP CONSTRAINT REQUESTS_EMPLOYEES_FK1;

ALTER TABLE SD.REQUESTS 
DROP CONSTRAINT REQUESTS_PRIORITY_TYPES_R_FK1;

ALTER TABLE SD.REQUESTS 
DROP CONSTRAINT REQUESTS_STATUSES_RF_FK;

ALTER TABLE SD.REQUESTS 
DROP CONSTRAINT REQUESTS_SUPPORT_GROUPS_FK;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_CATEGORIES_PM_FK;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_EMPLOYEES_FK;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_EMPLOYEES_FK1;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_IMPACT_TYPES_PM_FK;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_PRIORITY_TYPES_P_FK1;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_STATUSES_PM_FK;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_SUPPORT_GROUPS_FK;

ALTER TABLE SD.PROBLEMS 
DROP CONSTRAINT PROBLEMS_URGENCY_TYPES_PM_FK;

ALTER TABLE SD.INCIDENT_PROBLEM 
DROP CONSTRAINT INCIDENT_PROBLEM_INCIDENT_FK1;

ALTER TABLE SD.INCIDENT_PROBLEM 
DROP CONSTRAINT INCIDENT_PROBLEM_PROBLEMS_FK;

ALTER TABLE SD.INCIDENTS_HISTORY 
DROP CONSTRAINT INCIDENTS_HISTORY_INCIDEN_FK1;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_EMPLOYEES_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_EMPLOYEES_FK1;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_IMPACT_TYPES_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_INCIDENT_CATEGO_FK1;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_PRIORITY_TYPES_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_SERVICES_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_SOURCE_TYPES_IM_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_STATUSES_IM_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_SUPPORT_GROUPS_FK;

ALTER TABLE SD.INCIDENTS 
DROP CONSTRAINT INCIDENTS_URGENCY_TYPES_FK;

ALTER TABLE SD.IMPACT_URGENCY_IM 
DROP CONSTRAINT IMPACT_URGENCY_IMPACT_TYP_FK1;

ALTER TABLE SD.IMPACT_URGENCY_IM 
DROP CONSTRAINT IMPACT_URGENCY_PRIORITY_T_FK1;

ALTER TABLE SD.IMPACT_URGENCY_IM 
DROP CONSTRAINT IMPACT_URGENCY_URGENCY_TY_FK1;

ALTER TABLE SD.GROUP_MEMBER 
DROP CONSTRAINT GROUP_MEMBER_EMPLOYEES_FK;

ALTER TABLE SD.GROUP_MEMBER 
DROP CONSTRAINT GROUP_MEMBER_SUPPORT_GROU_FK1;

ALTER TABLE SD.EVENT_PARAMETERS 
DROP CONSTRAINT EVENT_PARAMETERS_EVENTS_FK;

ALTER TABLE SD.EVENT_INCIDENT 
DROP CONSTRAINT EVENT_INCIDENT_EVENTS_FK;

ALTER TABLE SD.EVENT_INCIDENT 
DROP CONSTRAINT EVENT_INCIDENT_INCIDENTS_FK;

ALTER TABLE SD.EVENTS 
DROP CONSTRAINT EVENTS_EVENT_CATEGORIES_FK;

ALTER TABLE SD.EVENTS 
DROP CONSTRAINT EVENTS_EVENT_SIGNIFICANCE_FK1;

ALTER TABLE SD.EVENTS 
DROP CONSTRAINT EVENTS_INCIDENTS_FK;

ALTER TABLE SD.EMPLOYEE_SERVICE 
DROP CONSTRAINT EMPLOYEE_SERVICE_AGREEMEN_FK1;

ALTER TABLE SD.EMPLOYEE_SERVICE 
DROP CONSTRAINT EMPLOYEE_SERVICE_EMPLOYEE_FK1;

ALTER TABLE SD.EMPLOYEE_SERVICE 
DROP CONSTRAINT EMPLOYEE_SERVICE_SERVICES_FK;

ALTER TABLE SD.COMMENTS 
DROP CONSTRAINT COMMENTS_EMPLOYEES_FK;

ALTER TABLE SD.COMMENTS 
DROP CONSTRAINT COMMENTS_INCIDENTS_FK;

ALTER TABLE SD.COMMENTS 
DROP CONSTRAINT COMMENTS_PROBLEMS_FK;

ALTER TABLE SD.COMMENTS 
DROP CONSTRAINT COMMENTS_REQUESTS_FK;

ALTER TABLE SD.CATEGORIES_RF 
DROP CONSTRAINT CATEGORIES_RF_CATEGORIES__FK1;

ALTER TABLE SD.CATEGORIES_PM 
DROP CONSTRAINT CATEGORIES_PM_CATEGORIES__FK1;

ALTER TABLE SD.CATEGORIES_IM 
DROP CONSTRAINT INCIDENT_CATEGORY_INCIDEN_FK1;

ALTER TABLE SD.CATEGORIES_EM 
DROP CONSTRAINT EVENT_CATEGORIES_EVENT_CA_FK1;

ALTER TABLE SD.EMPLOYEES 
DROP CONSTRAINT EMPLOYEES_DEPARTMENTS_FK;

ALTER TABLE SD.EMPLOYEES 
DROP CONSTRAINT EMPLOYEES_EMPLOYEES_FK;

ALTER TABLE SD.EMPLOYEES 
DROP CONSTRAINT EMPLOYEES_JOBS_FK;

ALTER TABLE SD.DEPARTMENTS 
DROP CONSTRAINT DEPARTMENTS_EMPLOYEES_FK;

ALTER TABLE SD.ANNOUNCEMENT_ATTACHMENTS 
DROP CONSTRAINT ANNOUNCEMENT_ATTACHMENTS__FK1;

ALTER TABLE SD.ANNOUNCEMENT_ATTACHMENTS 
DROP CONSTRAINT ANNOUNCEMENT_ATTACHMENTS__FK2;

ALTER TABLE SD.ANNOUNCEMENTS 
DROP CONSTRAINT ANNOUNCEMENTS_EMPLOYEES_FK1;

ALTER TABLE SD.C2_RELATION_CLASSES 
DROP CONSTRAINT C2_RELATION_CLASSES_C2_RE_FK1;

ALTER TABLE SD.C2_RELATION_CLASSES 
DROP CONSTRAINT C2_RELATION_CLASS_C2_CLAS_FK1;

ALTER TABLE SD.C2_RELATION_CLASSES 
DROP CONSTRAINT C2_RELATION_CLASS_C2_ITEM_FK1;

ALTER TABLE SD.C2_RELATION_CLASSES 
DROP CONSTRAINT C2_RELATION_CLASS_C2_ITEM_FK2;

ALTER TABLE SD.C2_RELATIONS 
DROP CONSTRAINT C2_RELATIONS_C2_ENTITIES_FK1;

ALTER TABLE SD.C2_RELATIONS 
DROP CONSTRAINT C2_RELATIONS_C2_ITEMS_FK1;

ALTER TABLE SD.C2_RELATIONS 
DROP CONSTRAINT C2_RELATIONS_C2_ITEMS_FK2;

ALTER TABLE SD.C2_RELATIONS 
DROP CONSTRAINT C2_RELATIONS_C2_RELATION__FK1;

ALTER TABLE SD.C2_ITEM_CLASSES 
DROP CONSTRAINT C2_ITEM_CLASSES_C2_ITEM_C_FK1;

ALTER TABLE SD.C2_ITEM_CLASSES 
DROP CONSTRAINT C2_ITEM_CLASS_C2_CLASS_FK1;

ALTER TABLE SD.C2_ITEMS_UNIVERSAL 
DROP CONSTRAINT C2_UNIVERSAL_ITEMS_C2_CLA_FK1;

ALTER TABLE SD.C2_ITEMS_UNIVERSAL 
DROP CONSTRAINT C2_UNIVERSAL_ITEMS_C2_ITE_FK1;

ALTER TABLE SD.C2_ITEMS_SERVICE 
DROP CONSTRAINT C2_SERVICE_ITEMS_C2_ITEMS_FK1;

ALTER TABLE SD.C2_ITEMS_SERVICE 
DROP CONSTRAINT C2_SERVICE_ITEMS_SERVICES_FK1;

ALTER TABLE SD.C2_ITEMS_RFC 
DROP CONSTRAINT C2_RFC_ITEMS_C2_ITEMS_FK1;

ALTER TABLE SD.C2_ITEMS_PROBLEM 
DROP CONSTRAINT C2_PROBLEM_ITEMS_C2_ITEMS_FK1;

ALTER TABLE SD.C2_ITEMS_PROBLEM 
DROP CONSTRAINT C2_PROBLEM_ITEMS_INCIDENT_FK1;

ALTER TABLE SD.C2_ITEMS_INCIDENT 
DROP CONSTRAINT C2_INCIDENT_ITEMS_C2_ITEM_FK1;

ALTER TABLE SD.C2_ITEMS_INCIDENT 
DROP CONSTRAINT C2_INCIDENT_ITEMS_INCIDEN_FK1;

ALTER TABLE SD.C2_ITEMS_EMPLOYEE 
DROP CONSTRAINT C2_EMPLOYEE_ITEMS_C2_ITEM_FK1;

ALTER TABLE SD.C2_ITEMS_EMPLOYEE 
DROP CONSTRAINT C2_EMPLOYEE_ITEMS_EMPLOYE_FK1;

ALTER TABLE SD.C2_ITEMS 
DROP CONSTRAINT C2_ITEMS_C2_ENTITIES_FK1;

ALTER TABLE SD.C2_CLASS_ATTRIBUTE_VALUES 
DROP CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_FK1;

ALTER TABLE SD.C2_CLASS_ATTRIBUTE_VALUES 
DROP CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_FK2;

ALTER TABLE SD.C2_CLASS_ATTRIBUTES 
DROP CONSTRAINT C2_CLASS_ATTRIBUTES_C2_CL_FK1;

ALTER TABLE SD.RFC 
DROP CONSTRAINT RFC_EMPLOYEES_FK1;

ALTER TABLE SD.RFC 
DROP CONSTRAINT RFC_RFC_IMPACT_FK1;

ALTER TABLE SD.RFC 
DROP CONSTRAINT RFC_RFC_PRIORITY_FK1;

DROP SEQUENCE SD.USERS_SEQ;

DROP SEQUENCE SD.SUPPORT_GROUP_ID;

DROP SEQUENCE SD.SOLUTION_ID_SEQ;

DROP SEQUENCE SD.SIGNAL_TYPE_ID_SEQ;

DROP SEQUENCE SD.SIGNAL_PARAM_ID_SEQ;

DROP SEQUENCE SD.SIGNAL_ID_SEQ;

DROP SEQUENCE SD.SIGNAL_GENERATOR_ID_SEQ;

DROP SEQUENCE SD.REQ_ATTR_ID_SEQ;

DROP SEQUENCE SD.PARAMETER_ID_SEQ;

DROP SEQUENCE SD.INCIDENT_HISTORY_ID_SEQ;

DROP SEQUENCE SD.HISTORY_ID_SEQ;

DROP SEQUENCE SD.HIBERNATE_SEQUENCE;

DROP SEQUENCE SD.EVENT_ID_SEQ;

DROP SEQUENCE SD.EMPLOYEE_ID_SEQ;

DROP SEQUENCE SD.COMMENT_ID_SEQ;

DROP SEQUENCE SD.ATTACHMENTS_SEQ;

DROP SEQUENCE SD.ANNOUNCEMENTS_SEQ;

DROP SEQUENCE SD.C2_ENTITIES_SEQ;

DROP SEQUENCE SD.C2_CLASS_SEQ;

DROP SEQUENCE SD.C2_CLASS_ATTRIBUTES_SEQ;

DROP SEQUENCE SD.RFC_SEQ;

DROP SEQUENCE SD.RFC_PRIORITY_SEQ;

DROP SEQUENCE SD.RFC_IMPACT_SEQ;

DROP TABLE SD.USER_ROLE CASCADE CONSTRAINTS;

DROP TABLE SD.USERS CASCADE CONSTRAINTS;

DROP TABLE SD.ROLE_PRIVILEGE CASCADE CONSTRAINTS;

DROP TABLE SD.ROLES CASCADE CONSTRAINTS;

DROP TABLE SD.PRIVILEGE_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.URGENCY_TYPES_PM CASCADE CONSTRAINTS;

DROP TABLE SD.URGENCY_TYPES_IM CASCADE CONSTRAINTS;

DROP TABLE SD.SUPPORT_GROUPS CASCADE CONSTRAINTS;

DROP TABLE SD.SUPPORTING_SERVICES CASCADE CONSTRAINTS;

DROP TABLE SD.STATUSES_RF CASCADE CONSTRAINTS;

DROP TABLE SD.STATUSES_PM CASCADE CONSTRAINTS;

DROP TABLE SD.STATUSES_IM CASCADE CONSTRAINTS;

DROP TABLE SD.SOURCE_TYPES_IM CASCADE CONSTRAINTS;

DROP TABLE SD.SOLUTION_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SOLUTION_CATEGORIES CASCADE CONSTRAINTS;

DROP TABLE SD.SOLUTIONS CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_SIGNIFICANCE_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_RECEIVER_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_OBJECT_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_OBJECT_ATTRIBUTE_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_GENERATORS CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNAL_ATTRIBUTES CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNALS_TMP CASCADE CONSTRAINTS;

DROP TABLE SD.SIGNALS CASCADE CONSTRAINTS;

DROP TABLE SD.SERVICE_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.SERVICE_MANAGERS CASCADE CONSTRAINTS;

DROP TABLE SD.SERVICES CASCADE CONSTRAINTS;

DROP TABLE SD.REQUEST_ATTRIBUTE_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.REQUEST_ATTRIBUTES CASCADE CONSTRAINTS;

DROP TABLE SD.REQUESTS CASCADE CONSTRAINTS;

DROP TABLE SD.PROBLEMS CASCADE CONSTRAINTS;

DROP TABLE SD.PRIORITY_TYPES_RF CASCADE CONSTRAINTS;

DROP TABLE SD.PRIORITY_TYPES_PM CASCADE CONSTRAINTS;

DROP TABLE SD.PRIORITY_TYPES_IM CASCADE CONSTRAINTS;

DROP TABLE SD.INCIDENT_PROBLEM CASCADE CONSTRAINTS;

DROP TABLE SD.INCIDENTS_HISTORY CASCADE CONSTRAINTS;

DROP TABLE SD.INCIDENTS CASCADE CONSTRAINTS;

DROP TABLE SD.IMPACT_URGENCY_IM CASCADE CONSTRAINTS;

DROP TABLE SD.IMPACT_TYPES_PM CASCADE CONSTRAINTS;

DROP TABLE SD.IMPACT_TYPES_IM CASCADE CONSTRAINTS;

DROP TABLE SD.GROUP_MEMBER CASCADE CONSTRAINTS;

DROP TABLE SD.EVENT_SIGNIFICANCE_TYPES CASCADE CONSTRAINTS;

DROP TABLE SD.EVENT_PARAMETERS CASCADE CONSTRAINTS;

DROP TABLE SD.EVENT_INCIDENT CASCADE CONSTRAINTS;

DROP TABLE SD.EVENTS CASCADE CONSTRAINTS;

DROP TABLE SD.EMPLOYEE_SERVICE CASCADE CONSTRAINTS;

DROP TABLE SD.COMMENTS CASCADE CONSTRAINTS;

DROP TABLE SD.CATEGORIES_RF CASCADE CONSTRAINTS;

DROP TABLE SD.CATEGORIES_PM CASCADE CONSTRAINTS;

DROP TABLE SD.CATEGORIES_IM CASCADE CONSTRAINTS;

DROP TABLE SD.CATEGORIES_EM CASCADE CONSTRAINTS;

DROP TABLE SD.AGREEMENTS CASCADE CONSTRAINTS;

DROP TABLE SD.JOBS CASCADE CONSTRAINTS;

DROP TABLE SD.EMPLOYEES CASCADE CONSTRAINTS;

DROP TABLE SD.DEPARTMENTS CASCADE CONSTRAINTS;

DROP TABLE SD.ATTACHMENTS CASCADE CONSTRAINTS;

DROP TABLE SD.ANNOUNCEMENT_ATTACHMENTS CASCADE CONSTRAINTS;

DROP TABLE SD.ANNOUNCEMENTS CASCADE CONSTRAINTS;

DROP TABLE SD.C2_RELATION_CLASSES CASCADE CONSTRAINTS;

DROP TABLE SD.C2_RELATIONS CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEM_CLASSES CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS_UNIVERSAL CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS_SERVICE CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS_RFC CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS_PROBLEM CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS_INCIDENT CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS_EMPLOYEE CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ITEMS CASCADE CONSTRAINTS;

DROP TABLE SD.C2_ENTITIES CASCADE CONSTRAINTS;

DROP TABLE SD.C2_CLASS_ATTRIBUTE_VALUES CASCADE CONSTRAINTS;

DROP TABLE SD.C2_CLASS_ATTRIBUTES CASCADE CONSTRAINTS;

DROP TABLE SD.C2_CLASSES CASCADE CONSTRAINTS;

DROP TABLE SD.RFC_PRIORITY CASCADE CONSTRAINTS;

DROP TABLE SD.RFC_IMPACT CASCADE CONSTRAINTS;

DROP TABLE SD.RFC CASCADE CONSTRAINTS;

CREATE TABLE SD.USER_ROLE 
(
  USER_ID NUMBER(10, 0) NOT NULL 
, ROLE_CODE VARCHAR2(40 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.USERS 
(
  USER_ID NUMBER(10) NOT NULL 
, LOGIN VARCHAR2(50 CHAR) NOT NULL 
, PASSWORD VARCHAR2(50 CHAR) NOT NULL 
, ENABLED CHAR(1 CHAR) NOT NULL 
, EMPLOYEE NUMBER(10) NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

CREATE TABLE SD.ROLE_PRIVILEGE 
(
  ROLE_CODE VARCHAR2(40 BYTE) NOT NULL 
, PRIVILEGE_CODE VARCHAR2(40 BYTE) NOT NULL 
, CONSTRAINT ROLE_PRIVILEGE_PK PRIMARY KEY 
  (
    ROLE_CODE 
  , PRIVILEGE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.ROLES 
(
  ROLE_CODE VARCHAR2(40 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT ROLES_PK PRIMARY KEY 
  (
    ROLE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.PRIVILEGE_TYPES 
(
  PRIVILEGE_CODE VARCHAR2(40 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT PRIVILEGE_TYPES_PK PRIMARY KEY 
  (
    PRIVILEGE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.URGENCY_TYPES_PM 
(
  URGENCY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT URGENCY_TYPES_PM_PK PRIMARY KEY 
  (
    URGENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.URGENCY_TYPES_IM 
(
  URGENCY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT URGENCY_TYPES_PK PRIMARY KEY 
  (
    URGENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SUPPORT_GROUPS 
(
  GROUP_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(30 BYTE) 
, MANAGER_ID NUMBER(10, 0) 
, CONSTRAINT SUPPORT_GROUPS_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SUPPORTING_SERVICES 
(
  SERVICE_ID NUMBER(10) NOT NULL 
, SUPPORTING_SERVICE_ID NUMBER(10) NOT NULL 
, CONSTRAINT SUPPORTING_SERVICES_PK PRIMARY KEY 
  (
    SERVICE_ID 
  , SUPPORTING_SERVICE_ID 
  )
  ENABLE 
);

CREATE TABLE SD.STATUSES_RF 
(
  STATUS_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT STATUSES_RF_PK PRIMARY KEY 
  (
    STATUS_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.STATUSES_PM 
(
  STATUS_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT STATUSES_PM_PK PRIMARY KEY 
  (
    STATUS_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.STATUSES_IM 
(
  STATUS_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(127 BYTE) 
, CONSTRAINT INCIDENTS_STATUSES_PK PRIMARY KEY 
  (
    STATUS_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SOURCE_TYPES_IM 
(
  SOURCE_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT SOURCE_TYPES_IM_PK PRIMARY KEY 
  (
    SOURCE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SOLUTION_TYPES 
(
  SOLUTION_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT SOLUTION_TYPES_PK PRIMARY KEY 
  (
    SOLUTION_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SOLUTION_CATEGORIES 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) 
, CONSTRAINT SOLUTION_CATEGORIES_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SOLUTIONS 
(
  SOLUTION_ID NUMBER(10, 0) NOT NULL 
, PROBLEM_ID NUMBER(10, 0) NOT NULL 
, SOLUTION_CODE CHAR(4 BYTE) NOT NULL 
, SUBJECT VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, AUTHOR NUMBER(10, 0) 
, LAST_UPDATE DATE 
, CONSTRAINT PROBLEM_SOLUTIONS_PK PRIMARY KEY 
  (
    SOLUTION_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_TYPES 
(
  TYPE_CODE NUMBER(10, 0) NOT NULL 
, MSG_TEMPLATE VARCHAR2(4000 BYTE) NOT NULL 
, SUBJECT_TEMPLATE VARCHAR2(400 BYTE) NOT NULL 
, SIGNIFICANCE_CODE CHAR(1 BYTE) NOT NULL 
, OBJECT_CODE CHAR(1 BYTE) NOT NULL 
, NAME VARCHAR2(1000 BYTE) 
, CONSTRAINT SIGNAL_TYPES_PK PRIMARY KEY 
  (
    TYPE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_SIGNIFICANCE_TYPES 
(
  SIGNIFICANCE_CODE CHAR(1 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CSS_CLASS VARCHAR2(100 BYTE) 
, CONSTRAINT SIGNAL_SIGNIFICANCE_TYPES_PK PRIMARY KEY 
  (
    SIGNIFICANCE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_RECEIVER_TYPES 
(
  RECEIVER_CODE CHAR(4 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, FROM_STATEMENT VARCHAR2(1000 BYTE) NOT NULL 
, CONSTRAINT SIGNAL_RECEIVER_TYPES_PK PRIMARY KEY 
  (
    RECEIVER_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_OBJECT_TYPES 
(
  OBJECT_CODE CHAR(1 BYTE) NOT NULL 
, VIEW_NAME VARCHAR2(30 BYTE) NOT NULL 
, ID_COLUMN_NAME VARCHAR2(30 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, DETAILS_URL VARCHAR2(100 BYTE) 
, CONSTRAINT SIGNAL_OBJECT_TYPES_PK PRIMARY KEY 
  (
    OBJECT_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_OBJECT_ATTRIBUTE_TYPES 
(
  ATTRIBUTE_CODE CHAR(4 BYTE) NOT NULL 
, ATTRIBUTE_NAME VARCHAR2(30 BYTE) NOT NULL 
, OBJECT_CODE CHAR(1 BYTE) NOT NULL 
, CONSTRAINT SIGNAL_PARAM_TYPES_PK PRIMARY KEY 
  (
    ATTRIBUTE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_GENERATORS 
(
  GENERATOR_ID NUMBER(8, 0) NOT NULL 
, TYPE_CODE NUMBER(10, 0) NOT NULL 
, CRITERION VARCHAR2(1000 BYTE) NOT NULL 
, SELECT_STATEMENT VARCHAR2(1000 BYTE) NOT NULL 
, RECEIVER_CODE CHAR(4 BYTE) NOT NULL 
, ENABLED CHAR(1 BYTE) NOT NULL 
, FREQUENCY NUMBER(3, 0) NOT NULL 
, LAST_RUN_STATUS CHAR(1 BYTE) 
, LAST_RUN_DATE DATE 
, ERROR_MESSAGE VARCHAR2(1000) 
, CONSTRAINT SIGNAL_GENERATORS_PK PRIMARY KEY 
  (
    GENERATOR_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SIGNAL_ATTRIBUTES 
(
  ATTRIBUTE_ID NUMBER(11, 0) NOT NULL 
, SIGNAL_ID NUMBER(10, 0) NOT NULL 
, ATTRIBUTE_CODE CHAR(4 BYTE) NOT NULL 
, ATTRIBUTE_VALUE VARCHAR2(1000 BYTE) 
, CONSTRAINT SIGNAL_PARAMS_PK PRIMARY KEY 
  (
    ATTRIBUTE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE GLOBAL TEMPORARY TABLE SD.SIGNALS_TMP 
(
  TYPE_CODE NUMBER(10, 0) NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) 
, OBJECT_ID NUMBER(10, 0) 
) 
ON COMMIT DELETE ROWS;

CREATE TABLE SD.SIGNALS 
(
  SIGNAL_ID NUMBER(10, 0) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, IS_SENT CHAR(1 BYTE) DEFAULT 'F' NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, TYPE_CODE NUMBER(10, 0) NOT NULL 
, OBJECT_ID NUMBER(10, 0) NOT NULL 
, ERROR_MESSAGE VARCHAR2(1000) 
, CONSTRAINT SIGNALS_PK PRIMARY KEY 
  (
    SIGNAL_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.SERVICE_TYPES 
(
  SERVICE_TYPE_CODE CHAR(4) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, CONSTRAINT SERVICE_TYPES_PK PRIMARY KEY 
  (
    SERVICE_TYPE_CODE 
  )
  ENABLE 
);

CREATE TABLE SD.SERVICE_MANAGERS 
(
  SERVICE_ID NUMBER(10) NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT SERVICE_MANAGERS_PK PRIMARY KEY 
  (
    SERVICE_ID 
  , EMPLOYEE_ID 
  )
  ENABLE 
);

CREATE TABLE SD.SERVICES 
(
  SERVICE_ID NUMBER(10) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, DESCRIPTION VARCHAR2(1000) NOT NULL 
, SERVICE_TYPE_CODE CHAR(4) NOT NULL 
, BUSINESS_IMPACT_CODE CHAR(4) NOT NULL 
, BUSINESS_PRIORITY_CODE CHAR(4) NOT NULL 
, AGREEMENT_ID NUMBER(10) NOT NULL 
, CONSTRAINT SERVICES_PK PRIMARY KEY 
  (
    SERVICE_ID 
  )
  ENABLE 
);

CREATE TABLE SD.REQUEST_ATTRIBUTE_TYPES 
(
  TYPE_CODE CHAR(6 BYTE) NOT NULL 
, REQUIRED CHAR(1 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, INPUT_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT REQUEST_ATTRIBUTE_TYPES_PK PRIMARY KEY 
  (
    TYPE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.REQUEST_ATTRIBUTES 
(
  ATTRIBUTE_ID NUMBER(10, 0) NOT NULL 
, REQUEST_ID NUMBER(10, 0) 
, TYPE_CODE CHAR(6 BYTE) 
, VALUE VARCHAR2(1000 BYTE) 
, CONSTRAINT REQUEST_ATTRIBUTES_PK PRIMARY KEY 
  (
    ATTRIBUTE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.REQUESTS 
(
  REQUEST_ID NUMBER(10, 0) NOT NULL 
, PRIORITY_CODE CHAR(4 BYTE) 
, STATUS_CODE CHAR(4 BYTE) DEFAULT 'OPEN' NOT NULL 
, CREATION_DATE DATE 
, AUTHOR NUMBER(10, 0) 
, CATEGORY_CODE CHAR(4 BYTE) 
, EMPLOYEE_ID NUMBER(10, 0) 
, CLOSURE_DATE DATE 
, TARGET_RESOLUTION_DATE DATE 
, STAFF_MEMBER NUMBER(10, 0) 
, GROUP_ID NUMBER(10, 0) 
, CONSTRAINT REQUESTS_PK PRIMARY KEY 
  (
    REQUEST_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.PROBLEMS 
(
  PROBLEM_ID NUMBER(10, 0) NOT NULL 
, IS_KNOWN_ERROR CHAR(1 BYTE) DEFAULT 'f' NOT NULL 
, SUBJECT VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, CLOSURE_DATE DATE 
, STATUS_CODE CHAR(4 BYTE) DEFAULT 'OPEN' NOT NULL 
, IMPACT_CODE CHAR(4 BYTE) 
, URGENCY_CODE CHAR(4 BYTE) 
, IMPACT_DETAILS VARCHAR2(1000 BYTE) 
, ROOT_CAUSE VARCHAR2(1000 BYTE) 
, SYMPTOMS VARCHAR2(1000 BYTE) 
, AUTHOR NUMBER(10, 0) NOT NULL 
, PRIORITY_CODE CHAR(4 BYTE) 
, STAFF_MEMBER NUMBER(10, 0) 
, GROUP_ID NUMBER(10, 0) 
, CONSTRAINT PROBLEMS_PK PRIMARY KEY 
  (
    PROBLEM_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.PRIORITY_TYPES_RF 
(
  PRIORITY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, TARGET_RESOLUTION_TIME NUMBER(2, 0) 
, CONSTRAINT PRIORITY_TYPES_RF_PK PRIMARY KEY 
  (
    PRIORITY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.PRIORITY_TYPES_PM 
(
  PRIORITY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT PRIORITY_TYPES_PM_PK PRIMARY KEY 
  (
    PRIORITY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.PRIORITY_TYPES_IM 
(
  PRIORITY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, TARGET_RESOLUTION_TIME NUMBER(2, 0) NOT NULL 
, CONSTRAINT PRIORITY_TYPES_PK PRIMARY KEY 
  (
    PRIORITY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.INCIDENT_PROBLEM 
(
  INCIDENT_ID NUMBER(10, 0) NOT NULL 
, PROBLEM_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT INCIDENT_PROBLEM_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  , PROBLEM_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.INCIDENTS_HISTORY 
(
  HISTORY_ID NUMBER(12, 0) NOT NULL 
, CHANGE_DATE DATE NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, INCIDENT_ID NUMBER(10, 0) NOT NULL 
, IMPACT_CODE CHAR(4 BYTE) 
, URGENCY_CODE CHAR(4 BYTE) 
, STATUS_CODE CHAR(4 BYTE) 
, REVIEW VARCHAR2(1024 BYTE) 
, PRIORITY_CODE CHAR(4 BYTE) 
, CATEGORY_CODE CHAR(4 BYTE) 
, SUBJECT VARCHAR2(100 BYTE) 
, DESCRIPTION VARCHAR2(4000 BYTE) 
, STAFF_MEMBER NUMBER(10, 0) 
, RESOLUTION VARCHAR2(4000 BYTE) 
, SOURCE_CODE CHAR(4 BYTE) 
, RESOLUTION_DATE DATE 
, GROUP_ID NUMBER(10, 0) 
, TARGET_RESOLUTION_DATE DATE 
, CLOSURE_DATE DATE 
, SERVICE_ID NUMBER(10) 
, CONSTRAINT INCIDENTS_HISTORY_PK PRIMARY KEY 
  (
    HISTORY_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.INCIDENTS 
(
  INCIDENT_ID NUMBER(10, 0) NOT NULL 
, IMPACT_CODE CHAR(4 BYTE) 
, URGENCY_CODE CHAR(4 BYTE) 
, STATUS_CODE CHAR(4 BYTE) DEFAULT 'OPEN' NOT NULL 
, REVIEW VARCHAR2(1024 BYTE) 
, PRIORITY_CODE CHAR(4 BYTE) 
, AUTHOR NUMBER(10, 0) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, CLOSURE_DATE DATE 
, SUBJECT VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, STAFF_MEMBER NUMBER(10, 0) 
, RESOLUTION VARCHAR2(4000 BYTE) 
, SOURCE_CODE CHAR(4 BYTE) 
, RESOLUTION_DATE DATE 
, GROUP_ID NUMBER(10, 0) 
, TARGET_RESOLUTION_DATE DATE 
, SERVICE_ID NUMBER(10) 
, CONSTRAINT INCIDENTS_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.IMPACT_URGENCY_IM 
(
  IMPACT_CODE CHAR(4 BYTE) NOT NULL 
, URGENCY_CODE CHAR(4 BYTE) NOT NULL 
, PRIORITY_CODE CHAR(4 BYTE) 
, CONSTRAINT IMPACT_URGENCY_PK PRIMARY KEY 
  (
    IMPACT_CODE 
  , URGENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.IMPACT_TYPES_PM 
(
  IMPACT_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT IMPACT_TYPES_PM_PK PRIMARY KEY 
  (
    IMPACT_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.IMPACT_TYPES_IM 
(
  IMPACT_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT IMPACT_TYPES_PK PRIMARY KEY 
  (
    IMPACT_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.GROUP_MEMBER 
(
  GROUP_ID NUMBER(10, 0) NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) 
, CONSTRAINT GROUP_MEMBER_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.EVENT_SIGNIFICANCE_TYPES 
(
  SIGNIFICANCE_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT EVENT_TYPES_PK PRIMARY KEY 
  (
    SIGNIFICANCE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.EVENT_PARAMETERS 
(
  PARAMETER_ID NUMBER(10, 0) NOT NULL 
, EVENT_ID NUMBER(10, 0) NOT NULL 
, PARAM_NAME VARCHAR2(200 BYTE) NOT NULL 
, PARAM_VALUE VARCHAR2(4000 BYTE) NOT NULL 
, CONSTRAINT EVENT_PARAMETERS_PK PRIMARY KEY 
  (
    PARAMETER_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.EVENT_INCIDENT 
(
  EVENT_ID NUMBER(10, 0) NOT NULL 
, INCIDENT_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT EVENT_INCIDENT_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  , EVENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.EVENTS 
(
  EVENT_ID NUMBER(10, 0) NOT NULL 
, SIGNIFICANCE_CODE CHAR(4 BYTE) NOT NULL 
, EVENT_DATE DATE NOT NULL 
, CREATION_DATE DATE NOT NULL 
, SUBJECT VARCHAR2(1000 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, INCIDENT_ID NUMBER(10, 0) 
, CONSTRAINT EVENTS_PK PRIMARY KEY 
  (
    EVENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.EMPLOYEE_SERVICE 
(
  EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, SERVICE_ID NUMBER(10) NOT NULL 
, AGREEMENT_ID NUMBER(10) 
, CONSTRAINT EMPLOYEE_SERVICE_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  , SERVICE_ID 
  )
  ENABLE 
);

CREATE TABLE SD.COMMENTS 
(
  COMMENT_ID NUMBER(10, 0) NOT NULL 
, TEXT VARCHAR2(4000 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, EVENT_ID NUMBER(10, 0) 
, EMPLOYEE_ID NUMBER(10, 0) 
, PROBLEM_ID NUMBER(10, 0) 
, INCIDENT_ID NUMBER(10, 0) 
, REQUEST_ID NUMBER(10, 0) 
, CONSTRAINT PROBLEM_COMMENTS_PK PRIMARY KEY 
  (
    COMMENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.CATEGORIES_RF 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, CONSTRAINT CATEGORIES_RF_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.CATEGORIES_PM 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, GROUP_ID NUMBER(10, 0) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, CONSTRAINT CATEGORIES_PM_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.CATEGORIES_IM 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(50 BYTE) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, GROUP_ID NUMBER(10, 0) 
, CONSTRAINT INCIDENT_CATEGORY_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.CATEGORIES_EM 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, CONSTRAINT EVENT_CATEGORIES_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.AGREEMENTS 
(
  AGREEMENT_ID NUMBER(10) NOT NULL 
, START_HOUR NUMBER(2) NOT NULL 
, END_HOUR NUMBER(2) NOT NULL 
, RESOLUTION_TIME NUMBER(2) NOT NULL 
, AVAILABILITY NUMBER(4, 2) 
, CONSTRAINT SLA_PK PRIMARY KEY 
  (
    AGREEMENT_ID 
  )
  ENABLE 
);

CREATE TABLE SD.JOBS 
(
  JOB_CODE VARCHAR2(10 BYTE) NOT NULL 
, JOB_TITLE VARCHAR2(35 BYTE) NOT NULL 
, CONSTRAINT JOB_ID_PK PRIMARY KEY 
  (
    JOB_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.EMPLOYEES 
(
  EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
, SURNAME VARCHAR2(30 BYTE) NOT NULL 
, PHONE_NUMBER VARCHAR2(20 BYTE) NOT NULL 
, MOBILE_PHONE VARCHAR2(20 BYTE) 
, EMAIL VARCHAR2(30 BYTE) NOT NULL 
, MANAGER_ID NUMBER(10, 0) 
, DEPARTMENT_ID NUMBER(4, 0) 
, JOB_CODE VARCHAR2(10 BYTE) 
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.DEPARTMENTS 
(
  DEPARTMENT_ID NUMBER(4, 0) NOT NULL 
, DEPARTMENT_NAME VARCHAR2(30 BYTE) NOT NULL 
, MANAGER_ID NUMBER(10, 0) 
, CONSTRAINT DEPT_ID_PK PRIMARY KEY 
  (
    DEPARTMENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SD.ATTACHMENTS 
(
  ATTACHMENT_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(500) NOT NULL 
, DATA BLOB NOT NULL 
, CONSTRAINT ATTACHMENTS_PK PRIMARY KEY 
  (
    ATTACHMENT_ID 
  )
  ENABLE 
);

CREATE TABLE SD.ANNOUNCEMENT_ATTACHMENTS 
(
  ANNOUNCEMENT_ID NUMBER(10, 0) NOT NULL 
, ATTACHMENT_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT ANNOUNCEMENT_ATTACHMENTS_PK PRIMARY KEY 
  (
    ANNOUNCEMENT_ID 
  , ATTACHMENT_ID 
  )
  ENABLE 
);

CREATE TABLE SD.ANNOUNCEMENTS 
(
  ANNOUNCEMENT_ID NUMBER(10, 0) NOT NULL 
, TITLE VARCHAR2(500) NOT NULL 
, CONTENT VARCHAR2(4000) NOT NULL 
, AUTHOR NUMBER(10, 0) NOT NULL 
, PUBLICATION_TIME DATE NOT NULL 
, CONSTRAINT ANNOUNCEMENTS_PK PRIMARY KEY 
  (
    ANNOUNCEMENT_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_RELATION_CLASSES 
(
  CLASS_ID NUMBER(10) NOT NULL 
, SOURCE_TYPE CHAR(3) NOT NULL 
, TARGET_TYPE CHAR(3) NOT NULL 
, LABEL VARCHAR2(200) NOT NULL 
, LABEL_REVERSE VARCHAR2(200) 
, PARENT_CLASS_ID NUMBER(10) 
, SOURCE_CLASS_ID NUMBER(10) 
, TARGET_CLASS_ID NUMBER(10) 
, CONSTRAINT C2_RELATION_DESCRIPTOR_PK PRIMARY KEY 
  (
    CLASS_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_RELATIONS 
(
  RELATION_ID NUMBER(10) NOT NULL 
, RELATION_CLASS_ID NUMBER(10) NOT NULL 
, SOURCE_ITEM_ID NUMBER(10) NOT NULL 
, TARGET_ITEM_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_RELATIONS_PK PRIMARY KEY 
  (
    RELATION_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEM_CLASSES 
(
  CLASS_ID NUMBER(10) NOT NULL 
, PARENT_CLASS_ID NUMBER(10) 
, CONSTRAINT C2_ITEM_DESCRIPTOR_PK PRIMARY KEY 
  (
    CLASS_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS_UNIVERSAL 
(
  ITEM_ID NUMBER(10) NOT NULL 
, CLASS_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_UNIVERSAL_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS_SERVICE 
(
  ITEM_ID NUMBER(10) NOT NULL 
, SERVICE_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_SERVICE_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS_RFC 
(
  ITEM_ID NUMBER(10) NOT NULL 
, RFC_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_RFC_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS_PROBLEM 
(
  ITEM_ID NUMBER(10) NOT NULL 
, PROBLEM_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_PROBLEM_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS_INCIDENT 
(
  ITEM_ID NUMBER(10) NOT NULL 
, INCIDENT_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_INCIDENT_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS_EMPLOYEE 
(
  ITEM_ID NUMBER(10) NOT NULL 
, EMPLOYEE_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_EMPLOYEE_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ITEMS 
(
  ITEM_ID NUMBER(10) NOT NULL 
, LABEL VARCHAR2(50) NOT NULL 
, CONSTRAINT C2_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_ENTITIES 
(
  ENTITY_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) DEFAULT 0 NOT NULL 
, CONSTRAINT C2_ITEM_BASE_PK PRIMARY KEY 
  (
    ENTITY_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_CLASS_ATTRIBUTE_VALUES 
(
  ENTITY_ID NUMBER(10) NOT NULL 
, ATTRIBITE_ID NUMBER(10) NOT NULL 
, VALUE VARCHAR2(2000) 
, CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_PK PRIMARY KEY 
  (
    ENTITY_ID 
  , ATTRIBITE_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_CLASS_ATTRIBUTES 
(
  ATTRIBUTE_ID NUMBER(10) NOT NULL 
, CLASS_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) DEFAULT 0 NOT NULL 
, NAME VARCHAR2(200) NOT NULL 
, DESCRIPTION VARCHAR2(2000) NOT NULL 
, DISPLAY_NO NUMBER(10) NOT NULL 
, IS_OVERVIEW CHAR(1) NOT NULL 
, CONSTRAINT C2_CLASS_ATTRIBUTES_PK PRIMARY KEY 
  (
    ATTRIBUTE_ID 
  )
  ENABLE 
);

CREATE TABLE SD.C2_CLASSES 
(
  CLASS_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) DEFAULT 0 NOT NULL 
, NAME VARCHAR2(200) NOT NULL 
, DESCRIPTION VARCHAR2(2000) NOT NULL 
, IS_ABSTRACT CHAR(1) NOT NULL 
, CONSTRAINT C2_CLASS_DESCRIPTOR_PK PRIMARY KEY 
  (
    CLASS_ID 
  )
  ENABLE 
);

CREATE TABLE SD.RFC_PRIORITY 
(
  ID NUMBER(10) NOT NULL 
, NAME VARCHAR2(200) NOT NULL 
, URGENT CHAR(1 BYTE) NOT NULL 
, VIEW_ORDER NUMBER(4) NOT NULL 
, CONSTRAINT RFC_PRIORITY_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE SD.RFC_IMPACT 
(
  ID NUMBER(10) NOT NULL 
, NAME VARCHAR2(200) NOT NULL 
, VIEW_ORDER NUMBER(4) NOT NULL 
, CONSTRAINT RFC_IMPACT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE SD.RFC 
(
  RFC_ID NUMBER(10, 0) NOT NULL 
, CREATIONTIME TIMESTAMP NOT NULL 
, AUTHOR NUMBER(10) NOT NULL 
, TITLE VARCHAR2(2000) NOT NULL 
, DESCRIPTION VARCHAR2(4000) NOT NULL 
, IMPACT NUMBER(10) 
, PRIORITY NUMBER(10) 
, CONSTRAINT RFC_PK PRIMARY KEY 
  (
    RFC_ID 
  )
  ENABLE 
);

ALTER TABLE SD.USERS
ADD CONSTRAINT USERS_UK1 UNIQUE 
(
  EMPLOYEE 
)
ENABLE;

ALTER TABLE SD.USERS
ADD CONSTRAINT USERS_UK2 UNIQUE 
(
  LOGIN 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS
ADD CONSTRAINT C2_ITEMS_UK1 UNIQUE 
(
  LABEL 
)
ENABLE;

ALTER TABLE SD.USER_ROLE
ADD CONSTRAINT EMPLOYEE_ROLE_EMPLOYEES_FK FOREIGN KEY
(
  USER_ID 
)
REFERENCES SD.USERS
(
  USER_ID 
)
ENABLE;

ALTER TABLE SD.USER_ROLE
ADD CONSTRAINT EMPLOYEE_ROLE_ROLES_FK1 FOREIGN KEY
(
  ROLE_CODE 
)
REFERENCES SD.ROLES
(
  ROLE_CODE 
)
ENABLE;

ALTER TABLE SD.USERS
ADD CONSTRAINT USERS_EMPLOYEES_FK1 FOREIGN KEY
(
  EMPLOYEE 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.ROLE_PRIVILEGE
ADD CONSTRAINT ROLE_PRIVILEGE_PRIVILEGE__FK1 FOREIGN KEY
(
  PRIVILEGE_CODE 
)
REFERENCES SD.PRIVILEGE_TYPES
(
  PRIVILEGE_CODE 
)
ENABLE;

ALTER TABLE SD.ROLE_PRIVILEGE
ADD CONSTRAINT ROLE_PRIVILEGE_ROLES_FK1 FOREIGN KEY
(
  ROLE_CODE 
)
REFERENCES SD.ROLES
(
  ROLE_CODE 
)
ENABLE;

ALTER TABLE SD.SUPPORTING_SERVICES
ADD CONSTRAINT SUPPORTING_SERVICES_SERVI_FK1 FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SD.SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SD.SUPPORTING_SERVICES
ADD CONSTRAINT SUPPORTING_SERVICES_SERVI_FK2 FOREIGN KEY
(
  SUPPORTING_SERVICE_ID 
)
REFERENCES SD.SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SD.SOLUTIONS
ADD CONSTRAINT PROBLEM_SOLUTIONS_PROBLEM_FK1 FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES SD.PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE SD.SOLUTIONS
ADD CONSTRAINT PROBLEM_SOLUTIONS_SOLUTIO_FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.SOLUTION_CATEGORIES
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.SOLUTIONS
ADD CONSTRAINT SOLUTIONS_EMPLOYEES_FK FOREIGN KEY
(
  AUTHOR 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.SOLUTIONS
ADD CONSTRAINT SOLUTIONS_SOLUTION_TYPES_FK FOREIGN KEY
(
  SOLUTION_CODE 
)
REFERENCES SD.SOLUTION_TYPES
(
  SOLUTION_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_TYPES
ADD CONSTRAINT SIGNAL_TYPES_SIGNAL_OBJEC_FK1 FOREIGN KEY
(
  OBJECT_CODE 
)
REFERENCES SD.SIGNAL_OBJECT_TYPES
(
  OBJECT_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_TYPES
ADD CONSTRAINT SIGNAL_TYPES_SIGNAL_SIGNI_FK FOREIGN KEY
(
  SIGNIFICANCE_CODE 
)
REFERENCES SD.SIGNAL_SIGNIFICANCE_TYPES
(
  SIGNIFICANCE_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_OBJECT_ATTRIBUTE_TYPES
ADD CONSTRAINT SIGNAL_OBJECT_ATTRIBUTE_TYP_FK FOREIGN KEY
(
  OBJECT_CODE 
)
REFERENCES SD.SIGNAL_OBJECT_TYPES
(
  OBJECT_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GENERATORS_RECEIVER_FK FOREIGN KEY
(
  RECEIVER_CODE 
)
REFERENCES SD.SIGNAL_RECEIVER_TYPES
(
  RECEIVER_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GENERATORS_SIGNAL_FK FOREIGN KEY
(
  TYPE_CODE 
)
REFERENCES SD.SIGNAL_TYPES
(
  TYPE_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_ATTRIBUTES
ADD CONSTRAINT SIGNAL_ATTRIBUTES_SIGNAL__FK1 FOREIGN KEY
(
  ATTRIBUTE_CODE 
)
REFERENCES SD.SIGNAL_OBJECT_ATTRIBUTE_TYPES
(
  ATTRIBUTE_CODE 
)
ENABLE;

ALTER TABLE SD.SIGNAL_ATTRIBUTES
ADD CONSTRAINT SIGNAL_PARAMS_SIGNALS_FK FOREIGN KEY
(
  SIGNAL_ID 
)
REFERENCES SD.SIGNALS
(
  SIGNAL_ID 
)
ENABLE;

ALTER TABLE SD.SERVICE_MANAGERS
ADD CONSTRAINT SERVICE_MANAGERS_EMPLOYEE_FK1 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.SERVICE_MANAGERS
ADD CONSTRAINT SERVICE_MANAGERS_SERVICES_FK FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SD.SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SD.SERVICES
ADD CONSTRAINT SERVICES_SERVICE_TYPES_FK FOREIGN KEY
(
  SERVICE_TYPE_CODE 
)
REFERENCES SD.SERVICE_TYPES
(
  SERVICE_TYPE_CODE 
)
ENABLE;

ALTER TABLE SD.SERVICES
ADD CONSTRAINT SERVICES_SLA_FK FOREIGN KEY
(
  AGREEMENT_ID 
)
REFERENCES SD.AGREEMENTS
(
  AGREEMENT_ID 
)
ENABLE;

ALTER TABLE SD.REQUEST_ATTRIBUTE_TYPES
ADD CONSTRAINT REQUEST_ATTRIBUTE_TYPES_C_FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.CATEGORIES_RF
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.REQUEST_ATTRIBUTES
ADD CONSTRAINT REQUEST_ATTRIBUTES_REQUES_FK1 FOREIGN KEY
(
  TYPE_CODE 
)
REFERENCES SD.REQUEST_ATTRIBUTE_TYPES
(
  TYPE_CODE 
)
ENABLE;

ALTER TABLE SD.REQUEST_ATTRIBUTES
ADD CONSTRAINT REQ_ATT_REQ_FK FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES SD.REQUESTS
(
  REQUEST_ID 
)
ENABLE;

ALTER TABLE SD.REQUESTS
ADD CONSTRAINT REQUESTS_CATEGORIES_RF_FK FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.CATEGORIES_RF
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.REQUESTS
ADD CONSTRAINT REQUESTS_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.REQUESTS
ADD CONSTRAINT REQUESTS_EMPLOYEES_FK1 FOREIGN KEY
(
  STAFF_MEMBER 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.REQUESTS
ADD CONSTRAINT REQUESTS_PRIORITY_TYPES_R_FK1 FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES SD.PRIORITY_TYPES_RF
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE SD.REQUESTS
ADD CONSTRAINT REQUESTS_STATUSES_RF_FK FOREIGN KEY
(
  STATUS_CODE 
)
REFERENCES SD.STATUSES_RF
(
  STATUS_CODE 
)
ENABLE;

ALTER TABLE SD.REQUESTS
ADD CONSTRAINT REQUESTS_SUPPORT_GROUPS_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SD.SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_CATEGORIES_PM_FK FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.CATEGORIES_PM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_EMPLOYEES_FK FOREIGN KEY
(
  AUTHOR 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_EMPLOYEES_FK1 FOREIGN KEY
(
  STAFF_MEMBER 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_IMPACT_TYPES_PM_FK FOREIGN KEY
(
  IMPACT_CODE 
)
REFERENCES SD.IMPACT_TYPES_PM
(
  IMPACT_CODE 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_PRIORITY_TYPES_P_FK1 FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES SD.PRIORITY_TYPES_PM
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_STATUSES_PM_FK FOREIGN KEY
(
  STATUS_CODE 
)
REFERENCES SD.STATUSES_PM
(
  STATUS_CODE 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_SUPPORT_GROUPS_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SD.SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE SD.PROBLEMS
ADD CONSTRAINT PROBLEMS_URGENCY_TYPES_PM_FK FOREIGN KEY
(
  URGENCY_CODE 
)
REFERENCES SD.URGENCY_TYPES_PM
(
  URGENCY_CODE 
)
ENABLE;

ALTER TABLE SD.INCIDENT_PROBLEM
ADD CONSTRAINT INCIDENT_PROBLEM_INCIDENT_FK1 FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES SD.INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENT_PROBLEM
ADD CONSTRAINT INCIDENT_PROBLEM_PROBLEMS_FK FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES SD.PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENTS_HISTORY
ADD CONSTRAINT INCIDENTS_HISTORY_INCIDEN_FK1 FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES SD.INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_EMPLOYEES_FK FOREIGN KEY
(
  AUTHOR 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_EMPLOYEES_FK1 FOREIGN KEY
(
  STAFF_MEMBER 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_IMPACT_TYPES_FK FOREIGN KEY
(
  IMPACT_CODE 
)
REFERENCES SD.IMPACT_TYPES_IM
(
  IMPACT_CODE 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_INCIDENT_CATEGO_FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.CATEGORIES_IM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_PRIORITY_TYPES_FK FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES SD.PRIORITY_TYPES_IM
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_SERVICES_FK FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SD.SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_SOURCE_TYPES_IM_FK FOREIGN KEY
(
  SOURCE_CODE 
)
REFERENCES SD.SOURCE_TYPES_IM
(
  SOURCE_CODE 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_STATUSES_IM_FK FOREIGN KEY
(
  STATUS_CODE 
)
REFERENCES SD.STATUSES_IM
(
  STATUS_CODE 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_SUPPORT_GROUPS_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SD.SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE SD.INCIDENTS
ADD CONSTRAINT INCIDENTS_URGENCY_TYPES_FK FOREIGN KEY
(
  URGENCY_CODE 
)
REFERENCES SD.URGENCY_TYPES_IM
(
  URGENCY_CODE 
)
ENABLE;

ALTER TABLE SD.IMPACT_URGENCY_IM
ADD CONSTRAINT IMPACT_URGENCY_IMPACT_TYP_FK1 FOREIGN KEY
(
  IMPACT_CODE 
)
REFERENCES SD.IMPACT_TYPES_IM
(
  IMPACT_CODE 
)
ENABLE;

ALTER TABLE SD.IMPACT_URGENCY_IM
ADD CONSTRAINT IMPACT_URGENCY_PRIORITY_T_FK1 FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES SD.PRIORITY_TYPES_IM
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE SD.IMPACT_URGENCY_IM
ADD CONSTRAINT IMPACT_URGENCY_URGENCY_TY_FK1 FOREIGN KEY
(
  URGENCY_CODE 
)
REFERENCES SD.URGENCY_TYPES_IM
(
  URGENCY_CODE 
)
ENABLE;

ALTER TABLE SD.GROUP_MEMBER
ADD CONSTRAINT GROUP_MEMBER_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.GROUP_MEMBER
ADD CONSTRAINT GROUP_MEMBER_SUPPORT_GROU_FK1 FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SD.SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE SD.EVENT_PARAMETERS
ADD CONSTRAINT EVENT_PARAMETERS_EVENTS_FK FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES SD.EVENTS
(
  EVENT_ID 
)
ENABLE;

ALTER TABLE SD.EVENT_INCIDENT
ADD CONSTRAINT EVENT_INCIDENT_EVENTS_FK FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES SD.EVENTS
(
  EVENT_ID 
)
ENABLE;

ALTER TABLE SD.EVENT_INCIDENT
ADD CONSTRAINT EVENT_INCIDENT_INCIDENTS_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES SD.INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE SD.EVENTS
ADD CONSTRAINT EVENTS_EVENT_CATEGORIES_FK FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.CATEGORIES_EM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.EVENTS
ADD CONSTRAINT EVENTS_EVENT_SIGNIFICANCE_FK1 FOREIGN KEY
(
  SIGNIFICANCE_CODE 
)
REFERENCES SD.EVENT_SIGNIFICANCE_TYPES
(
  SIGNIFICANCE_CODE 
)
ENABLE;

ALTER TABLE SD.EVENTS
ADD CONSTRAINT EVENTS_INCIDENTS_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES SD.INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE SD.EMPLOYEE_SERVICE
ADD CONSTRAINT EMPLOYEE_SERVICE_AGREEMEN_FK1 FOREIGN KEY
(
  AGREEMENT_ID 
)
REFERENCES SD.AGREEMENTS
(
  AGREEMENT_ID 
)
ENABLE;

ALTER TABLE SD.EMPLOYEE_SERVICE
ADD CONSTRAINT EMPLOYEE_SERVICE_EMPLOYEE_FK1 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.EMPLOYEE_SERVICE
ADD CONSTRAINT EMPLOYEE_SERVICE_SERVICES_FK FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SD.SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SD.COMMENTS
ADD CONSTRAINT COMMENTS_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.COMMENTS
ADD CONSTRAINT COMMENTS_INCIDENTS_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES SD.INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE SD.COMMENTS
ADD CONSTRAINT COMMENTS_PROBLEMS_FK FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES SD.PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE SD.COMMENTS
ADD CONSTRAINT COMMENTS_REQUESTS_FK FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES SD.REQUESTS
(
  REQUEST_ID 
)
ENABLE;

ALTER TABLE SD.CATEGORIES_RF
ADD CONSTRAINT CATEGORIES_RF_CATEGORIES__FK1 FOREIGN KEY
(
  PARENT_CATEGORY 
)
REFERENCES SD.CATEGORIES_RF
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.CATEGORIES_PM
ADD CONSTRAINT CATEGORIES_PM_CATEGORIES__FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SD.CATEGORIES_PM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.CATEGORIES_IM
ADD CONSTRAINT INCIDENT_CATEGORY_INCIDEN_FK1 FOREIGN KEY
(
  PARENT_CATEGORY 
)
REFERENCES SD.CATEGORIES_IM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.CATEGORIES_EM
ADD CONSTRAINT EVENT_CATEGORIES_EVENT_CA_FK1 FOREIGN KEY
(
  PARENT_CATEGORY 
)
REFERENCES SD.CATEGORIES_EM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SD.EMPLOYEES
ADD CONSTRAINT EMPLOYEES_DEPARTMENTS_FK FOREIGN KEY
(
  DEPARTMENT_ID 
)
REFERENCES SD.DEPARTMENTS
(
  DEPARTMENT_ID 
)
ENABLE;

ALTER TABLE SD.EMPLOYEES
ADD CONSTRAINT EMPLOYEES_EMPLOYEES_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.EMPLOYEES
ADD CONSTRAINT EMPLOYEES_JOBS_FK FOREIGN KEY
(
  JOB_CODE 
)
REFERENCES SD.JOBS
(
  JOB_CODE 
)
ENABLE;

ALTER TABLE SD.DEPARTMENTS
ADD CONSTRAINT DEPARTMENTS_EMPLOYEES_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.ANNOUNCEMENT_ATTACHMENTS
ADD CONSTRAINT ANNOUNCEMENT_ATTACHMENTS__FK1 FOREIGN KEY
(
  ANNOUNCEMENT_ID 
)
REFERENCES SD.ANNOUNCEMENTS
(
  ANNOUNCEMENT_ID 
)
ENABLE;

ALTER TABLE SD.ANNOUNCEMENT_ATTACHMENTS
ADD CONSTRAINT ANNOUNCEMENT_ATTACHMENTS__FK2 FOREIGN KEY
(
  ATTACHMENT_ID 
)
REFERENCES SD.ATTACHMENTS
(
  ATTACHMENT_ID 
)
ENABLE;

ALTER TABLE SD.ANNOUNCEMENTS
ADD CONSTRAINT ANNOUNCEMENTS_EMPLOYEES_FK1 FOREIGN KEY
(
  AUTHOR 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASSES_C2_RE_FK1 FOREIGN KEY
(
  PARENT_CLASS_ID 
)
REFERENCES SD.C2_RELATION_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_C2_CLAS_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES SD.C2_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_C2_ITEM_FK1 FOREIGN KEY
(
  SOURCE_CLASS_ID 
)
REFERENCES SD.C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_C2_ITEM_FK2 FOREIGN KEY
(
  TARGET_CLASS_ID 
)
REFERENCES SD.C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_ENTITIES_FK1 FOREIGN KEY
(
  RELATION_ID 
)
REFERENCES SD.C2_ENTITIES
(
  ENTITY_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_ITEMS_FK1 FOREIGN KEY
(
  SOURCE_ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_ITEMS_FK2 FOREIGN KEY
(
  TARGET_ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_RELATION__FK1 FOREIGN KEY
(
  RELATION_CLASS_ID 
)
REFERENCES SD.C2_RELATION_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEM_CLASSES
ADD CONSTRAINT C2_ITEM_CLASSES_C2_ITEM_C_FK1 FOREIGN KEY
(
  PARENT_CLASS_ID 
)
REFERENCES SD.C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEM_CLASSES
ADD CONSTRAINT C2_ITEM_CLASS_C2_CLASS_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES SD.C2_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_UNIVERSAL
ADD CONSTRAINT C2_UNIVERSAL_ITEMS_C2_CLA_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES SD.C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_UNIVERSAL
ADD CONSTRAINT C2_UNIVERSAL_ITEMS_C2_ITE_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_SERVICE
ADD CONSTRAINT C2_SERVICE_ITEMS_C2_ITEMS_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_SERVICE
ADD CONSTRAINT C2_SERVICE_ITEMS_SERVICES_FK1 FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SD.SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_RFC
ADD CONSTRAINT C2_RFC_ITEMS_C2_ITEMS_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_PROBLEM
ADD CONSTRAINT C2_PROBLEM_ITEMS_C2_ITEMS_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_PROBLEM
ADD CONSTRAINT C2_PROBLEM_ITEMS_INCIDENT_FK1 FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES SD.PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_INCIDENT
ADD CONSTRAINT C2_INCIDENT_ITEMS_C2_ITEM_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_INCIDENT
ADD CONSTRAINT C2_INCIDENT_ITEMS_INCIDEN_FK1 FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES SD.INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_EMPLOYEE
ADD CONSTRAINT C2_EMPLOYEE_ITEMS_C2_ITEM_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS_EMPLOYEE
ADD CONSTRAINT C2_EMPLOYEE_ITEMS_EMPLOYE_FK1 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.C2_ITEMS
ADD CONSTRAINT C2_ITEMS_C2_ENTITIES_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES SD.C2_ENTITIES
(
  ENTITY_ID 
)
ENABLE;

ALTER TABLE SD.C2_CLASS_ATTRIBUTE_VALUES
ADD CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_FK1 FOREIGN KEY
(
  ENTITY_ID 
)
REFERENCES SD.C2_ENTITIES
(
  ENTITY_ID 
)
ENABLE;

ALTER TABLE SD.C2_CLASS_ATTRIBUTE_VALUES
ADD CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_FK2 FOREIGN KEY
(
  ATTRIBITE_ID 
)
REFERENCES SD.C2_CLASS_ATTRIBUTES
(
  ATTRIBUTE_ID 
)
ENABLE;

ALTER TABLE SD.C2_CLASS_ATTRIBUTES
ADD CONSTRAINT C2_CLASS_ATTRIBUTES_C2_CL_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES SD.C2_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE SD.RFC
ADD CONSTRAINT RFC_EMPLOYEES_FK1 FOREIGN KEY
(
  AUTHOR 
)
REFERENCES SD.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SD.RFC
ADD CONSTRAINT RFC_RFC_IMPACT_FK1 FOREIGN KEY
(
  IMPACT 
)
REFERENCES SD.RFC_IMPACT
(
  ID 
)
ENABLE;

ALTER TABLE SD.RFC
ADD CONSTRAINT RFC_RFC_PRIORITY_FK1 FOREIGN KEY
(
  PRIORITY 
)
REFERENCES SD.RFC_PRIORITY
(
  ID 
)
ENABLE;

ALTER TABLE SD.USERS
ADD CONSTRAINT USERS_CHK1 CHECK 
(ENABLED IN ('Y', 'N'))
ENABLE;

ALTER TABLE SD.SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GEN_ENABLED_CHK CHECK 
(ENABLED IN ('T', 'F'))
ENABLE;

ALTER TABLE SD.SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GEN_STATUS_CHK CHECK 
(LAST_RUN_STATUS IN ('T', 'F'))
ENABLE;

ALTER TABLE SD.REQUEST_ATTRIBUTE_TYPES
ADD CONSTRAINT REQ_ATTR_REQUIRED_CHK CHECK 
(REQUIRED IN ('t', 'f'))
ENABLE;

ALTER TABLE SD.JOBS
ADD CONSTRAINT JOB_TITLE_NN CHECK 
(JOB_TITLE IS NOT NULL)
ENABLE;

ALTER TABLE SD.DEPARTMENTS
ADD CONSTRAINT DEPT_NAME_NN CHECK 
(DEPARTMENT_NAME IS NOT NULL)
ENABLE;

ALTER TABLE SD.C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_CHK1 CHECK 
((SOURCE_TYPE = 'UNI' AND SOURCE_CLASS_ID IS NOT NULL) OR (SOURCE_TYPE != 'UNI' AND SOURCE_CLASS_ID IS NULL) OR SOURCE_TYPE = 'ANY')
ENABLE;

ALTER TABLE SD.C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_CHK2 CHECK 
((TARGET_TYPE = 'UNI' AND TARGET_CLASS_ID IS NOT NULL) OR (TARGET_TYPE != 'UNI' AND TARGET_CLASS_ID IS NULL) OR TARGET_TYPE = 'ANY')
ENABLE;

ALTER TABLE SD.C2_CLASS_ATTRIBUTES
ADD CONSTRAINT C2_CLASS_ATTRIBUTES_CHK1 CHECK 
(IS_OVERVIEW IN ('Y', 'N'))
ENABLE;

ALTER TABLE SD.C2_CLASSES
ADD CONSTRAINT C2_CLASS_CHK1 CHECK 
(IS_ABSTRACT IN ('Y', 'N'))
ENABLE;

ALTER TABLE SD.RFC_PRIORITY
ADD CONSTRAINT RFC_PRIORITY_CHK1 CHECK 
(URGENT IN ('Y', 'N'))
ENABLE;

CREATE OR REPLACE VIEW SD.PROBLEMS_V AS select
  i.problem_id
  , i.subject
  , i.creation_date
  , extract(year from i.creation_date) as creation_year
  ,  'Q' || to_char(i.creation_date, 'Q ') as creation_quarter
  , extract(month from i.creation_date) as creation_month
  , extract(day from i.creation_date) as creation_day
  , to_char(i.creation_date, 'month') as creation_month_name
  , c.main_category
  , c.sub_category
  , c.sub_sub_category 
  , c.name as category
  , c.category_code
  , i.closure_date
  , extract(year from i.closure_date) as closure_year
  , extract(month from i.closure_date) as closure_month
  , extract(day from i.closure_date) as closure_day
  , to_char(i.closure_date, 'month') as closure_month_name
  , p.name as priority
  , p.priority_code
  , s.name as status
  , s.status_code
  , coalesce(e_gr.name || ' ' || e_gr.surname, 'BRAK') as staff_member
  , e_gr.employee_id as staff_member_id
  , coalesce(gr.name, 'BRAK') as support_group
  , gr.group_id
from
  problems i
  left join categories_pm_v c on i.category_code = c.category_code
  left join priority_types_pm p on p.priority_code = i.priority_code
  left join statuses_pm s on s.status_code = i.status_code
  left join employees e_gr on e_gr.employee_id = i.staff_member
  left join support_groups gr on gr.group_id = i.group_id;

CREATE OR REPLACE VIEW SD.KNOWN_ERRORS_V AS select p.problem_id, p.subject as subject, p.symptoms, p.root_cause, s.description as workaround, p.category_code
from solutions s join problems p on p.problem_id = s.problem_id
where s.solution_code = 'WORK' and p.is_known_error = 'T';

CREATE OR REPLACE VIEW SD.INCIDENTS_V AS SELECT i.incident_id ,
    i.subject ,
    i.creation_date ,
    extract(DAY FROM i.creation_date)   AS creation_day ,
    extract(YEAR FROM i.creation_date)  AS creation_year ,
    extract(MONTH FROM i.creation_date) AS creation_month ,
    'Q'
    || TO_CHAR(i.creation_date, 'Q ') AS creation_quarter ,
    TO_CHAR(i.creation_date, 'month') AS creation_month_name ,
    c.main_category ,
    c.sub_category ,
    c.sub_sub_category ,
    c.name AS category ,
    c.category_code,
    i.closure_date ,
    extract(YEAR FROM i.closure_date)  AS closure_year ,
    extract(MONTH FROM i.closure_date) AS closure_month ,
    extract(DAY FROM i.closure_date)   AS closure_day ,
    TO_CHAR(i.closure_date, 'month')   AS closure_month_name ,
    i.resolution_date ,
    extract(YEAR FROM i.resolution_date)  AS resolution_year ,
    extract(MONTH FROM i.resolution_date) AS resolution_month ,
    extract(DAY FROM i.resolution_date)   AS resolution_day ,
    TO_CHAR(i.resolution_date, 'month')   AS resolution_month_name ,
    i.target_resolution_date,
    COALESCE(p.name, 'NULL')              AS priority ,
    p.priority_code,
    COALESCE(s.name, 'NULL')              AS status ,
    s.status_code,
    COALESCE(sot.name, 'NULL')            AS source ,
    sot.source_code,
    COALESCE(e_gr.name
    || ' '
    || e_gr.surname, 'BRAK')  AS staff_member ,
    e_gr.employee_id as staff_member_id,
    COALESCE(gr.name, 'BRAK') AS support_group ,
    gr.group_id,
    i.author
  FROM incidents i
  LEFT JOIN categories_im_v c
  ON i.category_code = c.category_code
  LEFT JOIN priority_types_im p
  ON p.priority_code = i.priority_code
  LEFT JOIN statuses_im s
  ON s.status_code = i.status_code
  LEFT JOIN source_types_im sot
  ON sot.source_code = i.source_code
  LEFT JOIN employees e_gr
  ON e_gr.employee_id = i.staff_member
  LEFT JOIN support_groups gr
  ON gr.group_id = i.group_id;

CREATE OR REPLACE VIEW SD.EVENTS_V AS SELECT e.event_id,
    e.subject ,
    e.creation_date ,
    extract(YEAR FROM e.creation_date)  AS creation_year ,
    extract(MONTH FROM e.creation_date) AS creation_month ,
    TO_CHAR(e.creation_date, 'month')   AS creation_month_name ,
    e.event_date ,
    extract(YEAR FROM e.event_date)  AS event_year ,
    extract(MONTH FROM e.event_date) AS event_month ,
    TO_CHAR(e.event_date, 'month')   AS event_month_name ,
    c.main_category ,
    coalesce(c.sub_category, 'BRAK') as sub_category ,
    c.sub_sub_category ,
    c.name AS category ,
    es.name as significance,
    case when e.incident_id is NULL then 'NIE' else 'TAK' end as incident
FROM events e
LEFT JOIN categories_em_v c
ON e.category_code = c.category_code
LEFT JOIN event_significance_types es on es.significance_code = e.significance_code;

CREATE OR REPLACE VIEW SD.CATEGORIES_PM_V AS select
  c1.name as main_category, null as sub_category, null as sub_sub_category, category_code, name
from
  categories_pm c1
where
  c1.parent_category is null
union all
select
  c2.name as main_category, c1.name as sub_category, null as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
where
  c2.parent_category is null
union all
select
  c3.name as main_category, c2.name as sub_category, c1.name as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
  join categories_pm c3 on c2.parent_category = c3.category_code
where
  c3.parent_category is null
union all
select
  c4.name as main_category, c3.name as sub_category, c2.name as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
  join categories_pm c3 on c2.parent_category = c3.category_code
  join categories_pm c4 on c3.parent_category = c4.category_code
where
  c4.parent_category is null 
union all
select
  c5.name as main_category, c4.name as sub_category, c3.name as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
  join categories_pm c3 on c2.parent_category = c3.category_code
  join categories_pm c4 on c3.parent_category = c4.category_code
  join categories_pm c5 on c4.parent_category = c3.category_code
where
  c5.parent_category is null;

CREATE OR REPLACE VIEW SD.CATEGORIES_IM_V AS select
  c1.name as main_category, null as sub_category, null as sub_sub_category, category_code, name
from
  categories_im c1
where
  c1.parent_category is null
union all
select
  c2.name as main_category, c1.name as sub_category, null as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
where
  c2.parent_category is null
union all
select
  c3.name as main_category, c2.name as sub_category, c1.name as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
  join categories_im c3 on c2.parent_category = c3.category_code
where
  c3.parent_category is null
union all
select
  c4.name as main_category, c3.name as sub_category, c2.name as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
  join categories_im c3 on c2.parent_category = c3.category_code
  join categories_im c4 on c3.parent_category = c4.category_code
where
  c4.parent_category is null 
union all
select
  c5.name as main_category, c4.name as sub_category, c3.name as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
  join categories_im c3 on c2.parent_category = c3.category_code
  join categories_im c4 on c3.parent_category = c4.category_code
  join categories_im c5 on c4.parent_category = c3.category_code
where
  c5.parent_category is null;

CREATE OR REPLACE VIEW SD.CATEGORIES_EM_V AS SELECT c1.name AS main_category,
    NULL         AS sub_category,
    NULL         AS sub_sub_category,
    category_code,
    name
  FROM categories_em c1
  WHERE c1.parent_category IS NULL
  UNION ALL
  SELECT c2.name AS main_category,
    c1.name      AS sub_category,
    NULL         AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category     = c2.category_code
  WHERE c2.parent_category IS NULL
  UNION ALL
  SELECT c3.name AS main_category,
    c2.name      AS sub_category,
    c1.name      AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category = c2.category_code
  JOIN categories_em c3
  ON c2.parent_category     = c3.category_code
  WHERE c3.parent_category IS NULL
  UNION ALL
  SELECT c4.name AS main_category,
    c3.name      AS sub_category,
    c2.name      AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category = c2.category_code
  JOIN categories_em c3
  ON c2.parent_category = c3.category_code
  JOIN categories_em c4
  ON c3.parent_category     = c4.category_code
  WHERE c4.parent_category IS NULL
  UNION ALL
  SELECT c5.name AS main_category,
    c4.name      AS sub_category,
    c3.name      AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category = c2.category_code
  JOIN categories_em c3
  ON c2.parent_category = c3.category_code
  JOIN categories_em c4
  ON c3.parent_category = c4.category_code
  JOIN categories_em c5
  ON c4.parent_category     = c3.category_code
  WHERE c5.parent_category IS NULL;

COMMENT ON TABLE SD.USER_ROLE IS 'Tabela asocjacyjna zawieraj¹ca role przypisane dla danego pracownika';

COMMENT ON TABLE SD.ROLES IS 'S³ownik z mo¿liwymi rolami dla u¿ytkowników aplikacji.';

COMMENT ON TABLE SD.URGENCY_TYPES_PM IS 'S³ownik z typami pilnoœci dla problemów.';

COMMENT ON TABLE SD.URGENCY_TYPES_IM IS 'S³ownik z typami pilnoœci dla incydentów.';

COMMENT ON TABLE SD.SUPPORT_GROUPS IS 'Tabela z grupami wsparcia';

COMMENT ON TABLE SD.STATUSES_RF IS 'S³ownik z mo¿liwymi typami statusów dla zg³oszeñ.';

COMMENT ON TABLE SD.STATUSES_PM IS 'S³ownik z typami statusów dla problemów.';

COMMENT ON TABLE SD.STATUSES_IM IS 'S³ownik z mo¿liowymi statusami dla incydentów.';

COMMENT ON TABLE SD.SOLUTION_TYPES IS 'S³ownik z typami rozwi¹zañ. Mo¿e to byæ rozwi¹zanie sta³e jak i tymczasowe.';

COMMENT ON TABLE SD.SOLUTION_CATEGORIES IS 'S³ownik z typami kategorii rozwi¹zañ.';

COMMENT ON TABLE SD.SOLUTIONS IS 'Tabela zawieraj¹ca rozwi¹zania problemów.  S¹ to zarówno rozwi¹zania tymczasowe oraz rozwi¹zania sta³e.';

COMMENT ON TABLE SD.SIGNAL_TYPES IS 'Tabela zawieraj¹ca dane o typach sygna³ów.';

COMMENT ON TABLE SD.SIGNAL_SIGNIFICANCE_TYPES IS 'S³ownik mo¿liwych rang sygna³ów. Przyk³adowe rangi: informacja, ostrze¿enie, b³¹d.';

COMMENT ON TABLE SD.SIGNAL_RECEIVER_TYPES IS 'S³ownik mo¿liwych odbiorców sygna³ów.';

COMMENT ON TABLE SD.SIGNAL_OBJECT_TYPES IS 'Tabele zawieraj¹ce dane o typach obiektów. Przyk³adowe typy to: incydent, problem, zg³oszenie.';

COMMENT ON TABLE SD.SIGNAL_GENERATORS IS 'Zawiera informacje o generatorach sygna³ów.';

COMMENT ON TABLE SD.SIGNAL_ATTRIBUTES IS 'Zawiera informacje o wartoœciach atrybutów sygna³ów.';

COMMENT ON TABLE SD.SIGNALS_TMP IS 'Tabele tymczasowa przechowywuj¹ca dane o sygna³ach, które zostan¹ wygenerowany w zaistnieniu zdarzenia zmiany stanu. Trigger na poziomie wiersza wstawia dane do tej tabeli, natomiast trigger na poziomie tabeli pobiera wiersze z tej tabeli i wstawia do tabeli Signals.';

COMMENT ON TABLE SD.SIGNALS IS 'Zawiera informacje o sygna³ach.';

COMMENT ON TABLE SD.REQUEST_ATTRIBUTE_TYPES IS 'Tabela z typami atrybutów dla danej kateogrii zg³oszenia. Przyk³adowo je¿eli kategoria zg³oszenia jest to instalacja oprogramowania to typami atrybutów mog¹ byæ nazwa aplikacji oraz wersja aplikacji.';

COMMENT ON TABLE SD.REQUEST_ATTRIBUTES IS 'Tabela z wartoœciami atrybutów dla zg³oszeñ.';

COMMENT ON TABLE SD.REQUESTS IS 'Tabela z zg³oszeniami';

COMMENT ON TABLE SD.PROBLEMS IS 'Tabela z problemami';

COMMENT ON TABLE SD.PRIORITY_TYPES_RF IS 'S³ownik z mo¿liwymi typami priorytetów dla zg³oszeñ.';

COMMENT ON TABLE SD.PRIORITY_TYPES_PM IS 'S³ownik z typami priorytetów dla problemów.';

COMMENT ON TABLE SD.PRIORITY_TYPES_IM IS 'S³ownik z mo¿liwymi priorytetami dla incydentów.';

COMMENT ON TABLE SD.INCIDENT_PROBLEM IS 'Tabela asocjacyjna pomiêdzy problemami oraz incydentami.';

COMMENT ON TABLE SD.INCIDENTS_HISTORY IS 'Historia incydentów. Przy ka¿dej zmianie stanu incydentu wstawiany jest wiersz do tej tabeli.';

COMMENT ON TABLE SD.INCIDENTS IS 'Incydenty';

COMMENT ON TABLE SD.IMPACT_TYPES_PM IS 'S³ownik z typami wp³ywów dla problemów.';

COMMENT ON TABLE SD.IMPACT_TYPES_IM IS 'S³ownik z typami wp³ywów dla incydentów.';

COMMENT ON TABLE SD.GROUP_MEMBER IS 'Tabela asocjacyjna zawieraj¹ca listê cz³onków danej grupy wsparcia.';

COMMENT ON TABLE SD.EVENT_SIGNIFICANCE_TYPES IS 'S³ownik rang dla zdarzeñ. Przyk³adowe rangi to: informacje, ostrze¿enie, b³¹d.';

COMMENT ON TABLE SD.EVENT_PARAMETERS IS 'Lista wartoœci parametrów dla konkretnego zdarzenia.';

COMMENT ON TABLE SD.EVENT_INCIDENT IS 'Tabela asocjacyjna powi¹zuj¹ca zdarzenie z incydentem.';

COMMENT ON TABLE SD.EVENTS IS 'Zdarzenia';

COMMENT ON TABLE SD.COMMENTS IS 'Tabela z komentarzami';

COMMENT ON TABLE SD.CATEGORIES_RF IS 'S³ownik z mo¿liwymi typami kategorii dla zg³oszeñ.';

COMMENT ON TABLE SD.CATEGORIES_IM IS 'S³ownik z kategoriami incydentów';

COMMENT ON TABLE SD.CATEGORIES_EM IS 'S³ownik kategorii dla zdarzeñ.';

COMMENT ON TABLE SD.JOBS IS 'S³ownik z mo¿liwymi typami stanowisk.';

COMMENT ON TABLE SD.EMPLOYEES IS 'Tabela z pracownikami';

COMMENT ON TABLE SD.DEPARTMENTS IS 'S³ownik z departamentami.';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.TYPE_CODE IS 'Typ sygna³u';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.CRITERION IS 'Kryterium, które spe³niaj¹ obiekty';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.RECEIVER_CODE IS 'Typ odbiorcy';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.ENABLED IS 'Czy aktywny';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.FREQUENCY IS 'Czêstotliwoœæ w minutach';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.LAST_RUN_STATUS IS 'Status ostatnio wykonanej generacji.';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.LAST_RUN_DATE IS 'Data ostatniej generacji';

COMMENT ON COLUMN SD.SIGNAL_GENERATORS.ERROR_MESSAGE IS 'Komunikat bledu w trakcie generacji sygnalow';

COMMENT ON COLUMN SD.SIGNALS.ERROR_MESSAGE IS 'Komunikat bledu w trakcie wysylania sygnalu';

COMMENT ON COLUMN SD.PROBLEMS.IS_KNOWN_ERROR IS 'Czy to znany b³¹d';

COMMENT ON COLUMN SD.PROBLEMS.SUBJECT IS 'Temat problemu';

COMMENT ON COLUMN SD.PROBLEMS.DESCRIPTION IS 'Opis problemu';

COMMENT ON COLUMN SD.PROBLEMS.AUTHOR IS 'Pracownik, która doda³a problem';

COMMENT ON COLUMN SD.PROBLEMS.STAFF_MEMBER IS 'Serwisant do którego jest przypisany problem';

COMMENT ON COLUMN SD.PROBLEMS.GROUP_ID IS 'Grupa wsparcia do której jest przypisany problem';

COMMENT ON COLUMN SD.PRIORITY_TYPES_IM.TARGET_RESOLUTION_TIME IS 'Czas rozwi¹zania incydentu w godzinach.';

COMMENT ON COLUMN SD.COMMENTS.TEXT IS 'Treœæ komentarza';

COMMENT ON COLUMN SD.COMMENTS.CREATION_DATE IS 'Data dodania komentarza';

COMMENT ON COLUMN SD.COMMENTS.EMPLOYEE_ID IS 'Pracownik, który doda³ komentarz';

COMMENT ON COLUMN SD.CATEGORIES_IM.CATEGORY_CODE IS 'Identyfikator kategorii';

COMMENT ON COLUMN SD.CATEGORIES_IM.NAME IS 'Nazwa kategorii';

COMMENT ON COLUMN SD.CATEGORIES_IM.PARENT_CATEGORY IS 'Identyfikator kategorii nadrzêdnej';

COMMENT ON COLUMN SD.JOBS.JOB_CODE IS 'Primary key of jobs table.';

COMMENT ON COLUMN SD.JOBS.JOB_TITLE IS 'A not null column that shows job title, e.g. AD_VP, FI_ACCOUNTANT';

COMMENT ON COLUMN SD.DEPARTMENTS.DEPARTMENT_ID IS 'Primary key column of departments table.';

COMMENT ON COLUMN SD.DEPARTMENTS.DEPARTMENT_NAME IS 'A not null column that shows name of a department. Administration,
Marketing, Purchasing, Human Resources, Shipping, IT, Executive, Public
Relations, Sales, Finance, and Accounting. ';

COMMENT ON COLUMN SD.DEPARTMENTS.MANAGER_ID IS 'Manager_id of a department. Foreign key to employee_id column of employees table. The manager_id column of the employee table references this column.';

CREATE SEQUENCE SD.USERS_SEQ;

CREATE SEQUENCE SD.SUPPORT_GROUP_ID INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.SOLUTION_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.SIGNAL_TYPE_ID_SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.SIGNAL_PARAM_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.SIGNAL_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.SIGNAL_GENERATOR_ID_SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.REQ_ATTR_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.PARAMETER_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.INCIDENT_HISTORY_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.HISTORY_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.HIBERNATE_SEQUENCE INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.EVENT_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.EMPLOYEE_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.COMMENT_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SD.ATTACHMENTS_SEQ;

CREATE SEQUENCE SD.ANNOUNCEMENTS_SEQ;

CREATE SEQUENCE SD.C2_ENTITIES_SEQ START WITH 3000;

CREATE SEQUENCE SD.C2_CLASS_SEQ START WITH 3000;

CREATE SEQUENCE SD.C2_CLASS_ATTRIBUTES_SEQ START WITH 3000;

CREATE SEQUENCE SD.RFC_SEQ;

CREATE SEQUENCE SD.RFC_PRIORITY_SEQ;

CREATE SEQUENCE SD.RFC_IMPACT_SEQ;

CREATE OR REPLACE 
PACKAGE SD.APP 
AS 
  CURRENT_USER_ID NUMBER := 0;
  
  PROCEDURE set_user(user_id NUMBER);
  FUNCTION get_user RETURN NUMBER;

END APP;
/

CREATE OR REPLACE PACKAGE BODY APP AS



  PROCEDURE set_user(user_id NUMBER) AS
  BEGIN
    CURRENT_USER_ID := user_id;
  END set_user;

  FUNCTION get_user RETURN NUMBER AS
  BEGIN
    RETURN CURRENT_USER_ID;
  END get_user;

END APP;
/

CREATE OR REPLACE PROCEDURE SD.ADD_SIGNAL 
(
  type_code_v IN VARCHAR2  
, employee_id_v IN NUMBER  
, object_id_v IN NUMBER  
) AS
    object_code_v char;
    view_name_v varchar2(30);
    signal_id_v number;
    ir incidents_v%rowtype;
    pr problems_v%rowtype;
BEGIN
    select st.object_code, ot.view_name into object_code_v, view_name_v
    from signal_types st join signal_object_types ot on ot.object_code = st.object_code
    where st.type_code = type_code_v;
    
    insert into signals(SIGNAL_ID, CREATION_DATE,IS_SENT,EMPLOYEE_ID,TYPE_CODE,OBJECT_ID)
    values(signal_id_seq.nextval + 10000000 , sysdate, 'F', employee_id_v, type_code_v, object_id_v)
    returning signal_id
    INTO signal_id_v;
    

    IF object_code_v = 'I' THEN
        select * into ir from incidents_v where incident_id = object_id_v;
        
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISTA', ir.STATUS);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IPRI', ir.PRIORITY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSm', ir.RESOLUTION_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSd', ir.RESOLUTION_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSM', ir.RESOLUTION_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSY', ir.RESOLUTION_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSD', ir.RESOLUTION_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLm', ir.CLOSURE_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLd', ir.CLOSURE_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLM', ir.CLOSURE_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLY', ir.CLOSURE_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLD', ir.CLOSURE_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICTE', ir.CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICT3', ir.SUB_SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICT2', ir.SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICT1', ir.MAIN_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8m', ir.CREATION_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8Q', ir.CREATION_QUARTER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8M', ir.CREATION_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8Y', ir.CREATION_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8d', ir.CREATION_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8D', ir.CREATION_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISUB', ir.SUBJECT);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IID ', ir.INCIDENT_ID);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISG ', ir.SUPPORT_GROUP);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISM ', ir.STAFF_MEMBER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISRC', ir.SOURCE);
    
    ELSIF object_code_v = 'P' THEN
        select * into pr from problems_v where problem_id = object_id_v;
        
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSG ', pr.SUPPORT_GROUP);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSM ', pr.STAFF_MEMBER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSTA', pr.STATUS);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PPRI', pr.PRIORITY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLm', pr.CLOSURE_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLd', pr.CLOSURE_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLM', pr.CLOSURE_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLY', pr.CLOSURE_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLD', pr.CLOSURE_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT0', pr.CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT3', pr.SUB_SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT2', pr.SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT1', pr.MAIN_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8m', pr.CREATION_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8d', pr.CREATION_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8M', pr.CREATION_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8Q', pr.CREATION_QUARTER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8Y', pr.CREATION_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8D', pr.CREATION_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSUB', pr.SUBJECT);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PID ', pr.PROBLEM_ID);
    END IF;
/*

select
--ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE
    'insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval,signal_id_v,''' || soat.attribute_code || ''', r.' || soat.attribute_name || ');'
from
    user_tab_cols utc
    join signal_object_types sot on upper(utc.table_name) = upper(sot.view_name)
    join signal_object_attribute_types soat on soat.object_code = sot.object_code and upper(soat.attribute_name) = upper(utc.column_name)
where table_name = 'INCIDENTS_V'

*/

END ADD_SIGNAL;
/

CREATE OR REPLACE TRIGGER SD.INCIDENT_SIGNALS_TRG2 AFTER INSERT OR UPDATE ON INCIDENTS 
BEGIN
  FOR s IN (SELECT * FROM SIGNALS_TMP) LOOP
    ADD_SIGNAL(s.type_code, s.employee_id, s.object_id);
  END LOOP;
END;
/

CREATE OR REPLACE TRIGGER SD.INCIDENT_SIGNALS_TRG BEFORE INSERT OR UPDATE ON INCIDENTS 
FOR EACH ROW 
BEGIN
  IF :old.STATUS_CODE <> :new.STATUS_CODE THEN
    --powiadomienie autora o zmianie statusu
    insert into signals_tmp(type_code, employee_id, object_id) values(1, :new.AUTHOR, :new.INCIDENT_ID);
  END IF;
  
  IF coalesce(:old.STAFF_MEMBER,-1) <> coalesce(:new.STAFF_MEMBER,-1) THEN
    IF :old.STAFF_MEMBER is not NULL THEN
       --powiadomienie serwisanta o odpisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(11, :old.STAFF_MEMBER, :new.INCIDENT_ID);
    END IF;
    IF :new.STAFF_MEMBER is not NULL THEN
        --powiadomienie serwisanta o przypisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(10, :new.STAFF_MEMBER, :new.INCIDENT_ID);
    END IF;
  END IF;
  
  IF coalesce(:old.GROUP_ID,-1) <> coalesce(:new.GROUP_ID,-1) THEN
    IF :old.GROUP_ID is not NULL THEN    
       --powiadomienie menedzera grupy o odpisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(13, (select manager_id from support_groups where group_id = :old.GROUP_ID), :new.INCIDENT_ID);
    END IF;
    IF :new.GROUP_ID is not NULL THEN
        --powiadomienie menedzera grupy o przypisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(12, (select manager_id from support_groups where group_id = :new.GROUP_ID), :new.INCIDENT_ID);
    END IF;
  END IF;
  
END;
/

CREATE OR REPLACE TRIGGER SD.INCIDENT_HISTORY_TRG AFTER INSERT OR UPDATE ON INCIDENTS 
FOR EACH ROW
DECLARE
    history_id_v number;
    employee_id_v number;
BEGIN
  
  
  select HISTORY_ID_SEQ.nextval, app.get_user into history_id_v, employee_id_v from dual;
  
  insert into incidents_history(
    HISTORY_ID
    ,CHANGE_DATE
    ,EMPLOYEE_ID
    ,INCIDENT_ID
    ,IMPACT_CODE
    ,URGENCY_CODE
    ,STATUS_CODE
    ,REVIEW
    ,PRIORITY_CODE
    ,CATEGORY_CODE
    ,SUBJECT
    ,DESCRIPTION
    ,STAFF_MEMBER
    ,RESOLUTION
    ,SOURCE_CODE
    ,RESOLUTION_DATE
    ,GROUP_ID
    ,TARGET_RESOLUTION_DATE
  )
  values(
    history_id_v
    , sysdate
    , employee_id_v
    , :new.INCIDENT_ID
    , :new.IMPACT_CODE
    , :new.URGENCY_CODE
    , :new.STATUS_CODE
    , :new.REVIEW
    , :new.PRIORITY_CODE
    , :new.CATEGORY_CODE
    , :new.SUBJECT
    , :new.DESCRIPTION
    , :new.STAFF_MEMBER
    , :new.RESOLUTION
    , :new.SOURCE_CODE
    , :new.RESOLUTION_DATE
    , :new.GROUP_ID
    , :new.TARGET_RESOLUTION_DATE
  );
  
END;
/

CREATE OR REPLACE TRIGGER SD.c2_autoinsert_services AFTER INSERT ON services
    REFERENCING NEW AS service
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID, LABEL)
        VALUES (C2_ENTITIES_SEQ.currval, 'US£UGA #' || to_char(:service.SERVICE_ID));

    INSERT INTO C2_ITEMS_SERVICE (ITEM_ID, SERVICE_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :service.SERVICE_ID);
END;
/

CREATE OR REPLACE TRIGGER SD.c2_autoinsert_problems AFTER INSERT ON problems
    REFERENCING NEW AS problem
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID, LABEL)
        VALUES (C2_ENTITIES_SEQ.currval, 'PROBLEM #' || to_char(:problem.PROBLEM_ID));

    INSERT INTO C2_ITEMS_PROBLEM (ITEM_ID, PROBLEM_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :problem.PROBLEM_ID);
END;
/

CREATE OR REPLACE TRIGGER SD.c2_autoinsert_incidents AFTER INSERT ON incidents
    REFERENCING NEW AS incident
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID, LABEL)
        VALUES (C2_ENTITIES_SEQ.currval, 'INCYDENT #' || to_char(:incident.INCIDENT_ID));

    INSERT INTO C2_ITEMS_INCIDENT (ITEM_ID, INCIDENT_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :incident.INCIDENT_ID);
END;
/

CREATE OR REPLACE TRIGGER SD.c2_autoinsert_employees AFTER INSERT ON employees
    REFERENCING NEW AS employee
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID, LABEL)
        VALUES (C2_ENTITIES_SEQ.currval, 'PRACOWNIK #' || to_char(:employee.EMPLOYEE_ID));

    INSERT INTO C2_ITEMS_EMPLOYEE (ITEM_ID, EMPLOYEE_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :employee.EMPLOYEE_ID);
END;
/
