insert into departments(department_id, department_name) values(10, 'Administration');
insert into departments(department_id, department_name) values(20, 'Marketing');
insert into departments(department_id, department_name) values(30, 'Purchasing');
insert into departments(department_id, department_name) values(40, 'Human Resources');
insert into departments(department_id, department_name) values(50, 'Shipping');
insert into departments(department_id, department_name) values(60, 'IT');
insert into departments(department_id, department_name) values(70, 'Public Relations');
insert into departments(department_id, department_name) values(80, 'Sales');
insert into departments(department_id, department_name) values(90, 'Executive');
insert into departments(department_id, department_name) values(100, 'Finance');
insert into departments(department_id, department_name) values(110, 'Accounting');
insert into departments(department_id, department_name) values(120, 'Treasury');
insert into departments(department_id, department_name) values(130, 'Corporate Tax');
insert into departments(department_id, department_name) values(140, 'Control And Credit');
insert into departments(department_id, department_name) values(150, 'Shareholder Services');
insert into departments(department_id, department_name) values(160, 'Benefits');
insert into departments(department_id, department_name) values(170, 'Manufacturing');
insert into departments(department_id, department_name) values(180, 'Construction');
insert into departments(department_id, department_name) values(190, 'Contracting');
insert into departments(department_id, department_name) values(200, 'Operations');
insert into departments(department_id, department_name) values(210, 'IT Support');
insert into departments(department_id, department_name) values(220, 'NOC');
insert into departments(department_id, department_name) values(230, 'IT Helpdesk');
insert into departments(department_id, department_name) values(240, 'Government Sales');
insert into departments(department_id, department_name) values(250, 'Retail Sales');
insert into departments(department_id, department_name) values(260, 'Recruiting');
insert into departments(department_id, department_name) values(270, 'Payroll');