INSERT INTO RFC_PRIORITY(ID, NAME, URGENT, VIEW_ORDER) VALUES (1, 'Niski', 'N', 1000);
INSERT INTO RFC_PRIORITY(ID, NAME, URGENT, VIEW_ORDER) VALUES (2, 'Œredni', 'N', 2000);
INSERT INTO RFC_PRIORITY(ID, NAME, URGENT, VIEW_ORDER) VALUES (3, 'Wysoki', 'N', 3000);
INSERT INTO RFC_PRIORITY(ID, NAME, URGENT, VIEW_ORDER) VALUES (4, 'Pilny', 'Y', 4000);

INSERT INTO RFC_IMPACT(ID, NAME, VIEW_ORDER) VALUES (1, 'Ma³y', 1000);
INSERT INTO RFC_IMPACT(ID, NAME, VIEW_ORDER) VALUES (2, 'Œredni', 2000);
INSERT INTO RFC_IMPACT(ID, NAME, VIEW_ORDER) VALUES (3, 'Du¿y', 3000);
INSERT INTO RFC_IMPACT(ID, NAME, VIEW_ORDER) VALUES (4, 'Katastrofalny', 4000);