CREATE TABLE RFC 
(
  RFC_ID NUMBER(10) NOT NULL 
, CONSTRAINT RFC_PK PRIMARY KEY 
  (
    RFC_ID 
  )
  ENABLE 
);

CREATE TABLE CIITEM_TYPE 
(
  ITEM_TYPE_ID NUMBER(10) NOT NULL 
, PARENT_ITEM_TYPE_ID NUMBER(10) 
, NAME VARCHAR2(50) NOT NULL 
, ISABSTRACT CHAR(1) NOT NULL 
, ICON_BIG_URL VARCHAR2(100) 
, ICON_SMALL_URL VARCHAR2(100) 
, CONSTRAINT CIGENERIC_TYPE_PK PRIMARY KEY 
  (
    ITEM_TYPE_ID 
  )
  ENABLE 
);

CREATE TABLE CIITEM_ATTRIBUTE_VALUE 
(
  CIID NUMBER(10) NOT NULL 
, ITEM_TYPE_ID NUMBER(10) NOT NULL 
, ATTRIBUTE_NO NUMBER(10) NOT NULL 
, VALUE VARCHAR(2000) 
, CONSTRAINT CIITEM_ATTRIBUTE_VALUE_PK PRIMARY KEY 
  (
    CIID 
  , ITEM_TYPE_ID 
  , ATTRIBUTE_NO 
  )
  ENABLE 
);

CREATE TABLE CIITEM_ATTRIBUTE 
(
  ITEM_TYPE_ID NUMBER(10) NOT NULL 
, ATTRIBUTE_NO NUMBER(10) NOT NULL 
, ISREQUIRED CHAR(1) NOT NULL 
, NAME VARCHAR2(30) NOT NULL 
, FORMAT VARCHAR2(200) NOT NULL 
, CONSTRAINT CIGENERIC_ATTRIBUTE_PK PRIMARY KEY 
  (
    ITEM_TYPE_ID 
  , ATTRIBUTE_NO 
  )
  ENABLE 
);

CREATE TABLE CIITEM 
(
  CIID NUMBER(10) NOT NULL 
, PARENT_CIID NUMBER(10) NOT NULL 
, ITEM_TYPE_ID NUMBER(10) NOT NULL 
, TYPE CHAR(1) NOT NULL 
, BASELINE_ID NUMBER(10) 
, CONSTRAINT CIENTITY_PK PRIMARY KEY 
  (
    CIID 
  )
  ENABLE 
);

CREATE TABLE CIBASE 
(
  CIID NUMBER(10) NOT NULL 
, TYPE CHAR(3) NOT NULL 
, RFC_ID NUMBER(10) 
, EMPLOYEE_ID NUMBER(10) 
, CONSTRAINT CIBASE_PK PRIMARY KEY 
  (
    CIID 
  )
  ENABLE 
);

CREATE TABLE CIASSOCIATION_TYPE 
(
  ASSOCIATION_TYPE_ID NUMBER(10) NOT NULL 
, NAME VARCHAR2(50) NOT NULL 
, NAME_REVERSE VARCHAR2(50) 
, QUANTITY CHAR(1) NOT NULL 
, SOURCE_TYPE CHAR(3) NOT NULL 
, TARGET_TYPE CHAR(3) NOT NULL 
, SOURCE_ENTITY_TYPE_ID NUMBER(10) 
, TARGET_ENTITY_TYPE_ID NUMBER(10) 
, CONSTRAINT CIASSOCIATION_ROLE_PK PRIMARY KEY 
  (
    ASSOCIATION_TYPE_ID 
  )
  ENABLE 
);

CREATE TABLE CIASSOCIATION 
(
  ASSOCIATION_ID NUMBER(10) NOT NULL 
, ASSOCIATION_TYPE_ID NUMBER(10) NOT NULL 
, SOURCE_CIID NUMBER(10) NOT NULL 
, TARGET_CIID NUMBER(10) NOT NULL 
, CONSTRAINT CIASSOCIATION_PK PRIMARY KEY 
  (
    ASSOCIATION_ID 
  )
  ENABLE 
);

ALTER TABLE CIITEM_TYPE
ADD CONSTRAINT CIITEM_TYPE_UK_NAME UNIQUE 
(
  NAME 
)
ENABLE;

ALTER TABLE CIITEM_ATTRIBUTE
ADD CONSTRAINT CIITEM_ATTRIBUTE_UK_NAME UNIQUE 
(
  ITEM_TYPE_ID 
, NAME 
)
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_UK_EMPLOYEE UNIQUE 
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_UK_RFC UNIQUE 
(
  RFC_ID 
)
ENABLE;

ALTER TABLE CIASSOCIATION
ADD CONSTRAINT CIASSOCIATION_UK UNIQUE 
(
  ASSOCIATION_TYPE_ID 
, SOURCE_CIID 
, TARGET_CIID 
)
ENABLE;

ALTER TABLE CIITEM_TYPE
ADD CONSTRAINT CIITEM_TYPE_FK_PARENT FOREIGN KEY
(
  PARENT_ITEM_TYPE_ID 
)
REFERENCES CIITEM_TYPE
(
  ITEM_TYPE_ID 
)
ENABLE;

ALTER TABLE CIITEM_ATTRIBUTE_VALUE
ADD CONSTRAINT CIITEM_ATTRIBUTE_VALUE_FK_AT FOREIGN KEY
(
  ITEM_TYPE_ID 
, ATTRIBUTE_NO 
)
REFERENCES CIITEM_ATTRIBUTE
(
  ITEM_TYPE_ID 
, ATTRIBUTE_NO 
)
ENABLE;

ALTER TABLE CIITEM_ATTRIBUTE_VALUE
ADD CONSTRAINT CIITEM_ATTRIBUTE_VALUE_FK_EN FOREIGN KEY
(
  CIID 
)
REFERENCES CIITEM
(
  CIID 
)
ENABLE;

ALTER TABLE CIITEM_ATTRIBUTE
ADD CONSTRAINT CIITEM_ATTRIBUTE_FK_TYPE FOREIGN KEY
(
  ITEM_TYPE_ID 
)
REFERENCES CIITEM_TYPE
(
  ITEM_TYPE_ID 
)
ENABLE;

ALTER TABLE CIITEM
ADD CONSTRAINT CIITEM_FK_BASE FOREIGN KEY
(
  CIID 
)
REFERENCES CIBASE
(
  CIID 
)
ENABLE;

ALTER TABLE CIITEM
ADD CONSTRAINT CIITEM_FK_BASELINE FOREIGN KEY
(
  BASELINE_ID 
)
REFERENCES CIITEM
(
  CIID 
)
ENABLE;

ALTER TABLE CIITEM
ADD CONSTRAINT CIITEM_FK_PARENT FOREIGN KEY
(
  PARENT_CIID 
)
REFERENCES CIITEM
(
  CIID 
)
ENABLE;

ALTER TABLE CIITEM
ADD CONSTRAINT CIITEM_FK_TYPE FOREIGN KEY
(
  ITEM_TYPE_ID 
)
REFERENCES CIITEM_TYPE
(
  ITEM_TYPE_ID 
)
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_FK_EMPLOYEES FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_FK_RFC FOREIGN KEY
(
  RFC_ID 
)
REFERENCES RFC
(
  RFC_ID 
)
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_TYPE_FK_SOURCE FOREIGN KEY
(
  SOURCE_ENTITY_TYPE_ID 
)
REFERENCES CIITEM_TYPE
(
  ITEM_TYPE_ID 
)
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_TYPE_FK_TARGET FOREIGN KEY
(
  TARGET_ENTITY_TYPE_ID 
)
REFERENCES CIITEM_TYPE
(
  ITEM_TYPE_ID 
)
ENABLE;

ALTER TABLE CIASSOCIATION
ADD CONSTRAINT CIASSOCIATION_FK_SOURCE FOREIGN KEY
(
  SOURCE_CIID 
)
REFERENCES CIBASE
(
  CIID 
)
ENABLE;

ALTER TABLE CIASSOCIATION
ADD CONSTRAINT CIASSOCIATION_FK_TARGET FOREIGN KEY
(
  TARGET_CIID 
)
REFERENCES CIBASE
(
  CIID 
)
ENABLE;

ALTER TABLE CIASSOCIATION
ADD CONSTRAINT CIASSOCIATION_FK_TYPE FOREIGN KEY
(
  ASSOCIATION_TYPE_ID 
)
REFERENCES CIASSOCIATION_TYPE
(
  ASSOCIATION_TYPE_ID 
)
ENABLE;

ALTER TABLE CIITEM_TYPE
ADD CONSTRAINT CIITEM_TYPE_CHK_ISABSTRACT CHECK 
(ISABSTRACT = 'Y' OR ISABSTRACT = 'N')
ENABLE;

ALTER TABLE CIITEM_ATTRIBUTE
ADD CONSTRAINT CIITEM_ATTRIBUTE_CHK_ISREQU CHECK 
(ISREQUIRED = 'Y' OR ISREQUIRED = 'N')
ENABLE;

ALTER TABLE CIITEM
ADD CONSTRAINT CIITEM_CHK_TYPE CHECK 
(TYPE = 'E' OR TYPE = 'B' OR TYPE = 'V')
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_CHK_EMPLOYEE CHECK 
(TYPE != 'EMP' OR (RFC_ID IS NULL AND EMPLOYEE_ID IS NOT NULL))
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_CHK_RFC CHECK 
(TYPE != 'RFC' OR (RFC_ID IS NOT NULL AND EMPLOYEE_ID IS NULL))
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_CHK_TYPE CHECK 
(TYPE IN ('ENT', 'RFC', 'EMP'))
ENABLE;

ALTER TABLE CIBASE
ADD CONSTRAINT CIBASE_CHK_TYPE_ENTITY CHECK 
(TYPE != 'ENT' OR (RFC_ID IS NULL AND EMPLOYEE_ID IS NULL))
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_CHK_QUANTITY CHECK 
(QUANTITY = '1' OR QUANTITY = '?' OR QUANTITY = '*' OR QUANTITY = '+')
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_CHK_SOURCE_ENT CHECK 
((SOURCE_TYPE != 'ENT' AND SOURCE_ENTITY_TYPE_ID IS NULL) OR (SOURCE_TYPE = 'ENT' AND SOURCE_ENTITY_TYPE_ID IS NOT NULL))
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_CHK_SOURCE_TYPE CHECK 
(SOURCE_TYPE IN ('ENT', 'RFC', 'EMP'))
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_CHK_TARGET_ENT CHECK 
((TARGET_TYPE != 'ENT' AND TARGET_ENTITY_TYPE_ID IS NULL) OR (TARGET_TYPE = 'ENT' AND TARGET_ENTITY_TYPE_ID IS NOT NULL))
ENABLE;

ALTER TABLE CIASSOCIATION_TYPE
ADD CONSTRAINT CIASSOCIATION_CHK_TARGET_TYPE CHECK 
(TARGET_TYPE IN ('ENT', 'RFC', 'EMP'))
ENABLE;

CREATE SEQUENCE RFC_SEQ;

CREATE SEQUENCE CIITEM_TYPE_SEQ;

CREATE SEQUENCE CIITEM_ATTRIBUTE_SEQ;

CREATE SEQUENCE CIBASE_SEQ;

CREATE SEQUENCE CIASSOCIATION_TYPE_SEQ;

CREATE SEQUENCE CIASSOCIATION_SEQ;

CREATE TRIGGER RFC_TRG BEFORE INSERT ON RFC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.RFC_ID IS NULL THEN
      SELECT RFC_SEQ.NEXTVAL INTO :NEW.RFC_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER CIITEM_TYPE_TRG BEFORE INSERT ON CIITEM_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ITEM_TYPE_ID IS NULL THEN
      SELECT CIITEM_TYPE_SEQ.NEXTVAL INTO :NEW.ITEM_TYPE_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER CIITEM_ATTRIBUTE_TRG BEFORE INSERT ON CIITEM_ATTRIBUTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ITEM_TYPE_ID IS NULL THEN
      SELECT CIITEM_ATTRIBUTE_SEQ.NEXTVAL INTO :NEW.ITEM_TYPE_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER CIBASE_TRG BEFORE INSERT ON CIBASE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CIID IS NULL THEN
      SELECT CIBASE_SEQ.NEXTVAL INTO :NEW.CIID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER CIASSOCIATION_TYPE_TRG BEFORE INSERT ON CIASSOCIATION_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ASSOCIATION_TYPE_ID IS NULL THEN
      SELECT CIASSOCIATION_TYPE_SEQ.NEXTVAL INTO :NEW.ASSOCIATION_TYPE_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TRIGGER CIASSOCIATION_TRG BEFORE INSERT ON CIASSOCIATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ASSOCIATION_ID IS NULL THEN
      SELECT CIASSOCIATION_SEQ.NEXTVAL INTO :NEW.ASSOCIATION_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
