CREATE TABLE C2_RELATION_CLASSES 
(
  CLASS_ID NUMBER(10) NOT NULL 
, QUANTITY CHAR(1) NOT NULL 
, SOURCE_TYPE CHAR(3) NOT NULL 
, TARGET_TYPE CHAR(3) NOT NULL 
, LABEL VARCHAR2(200) NOT NULL 
, LABEL_REVERSE VARCHAR2(200) 
, PARENT_CLASS_ID NUMBER(10) 
, SOURCE_CLASS_ID NUMBER(10) 
, TARGET_CLASS_ID NUMBER(10) 
, CONSTRAINT C2_RELATION_DESCRIPTOR_PK PRIMARY KEY 
  (
    CLASS_ID 
  )
  ENABLE 
);

CREATE TABLE C2_RELATIONS 
(
  RELATION_ID NUMBER(10) NOT NULL 
, RELATION_CLASS_ID NUMBER(10) NOT NULL 
, SOURCE_ITEM_ID NUMBER(10) NOT NULL 
, TARGET_ITEM_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_RELATIONS_PK PRIMARY KEY 
  (
    RELATION_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEM_CLASSES 
(
  CLASS_ID NUMBER(10) NOT NULL 
, PARENT_CLASS_ID NUMBER(10) 
, CONSTRAINT C2_ITEM_DESCRIPTOR_PK PRIMARY KEY 
  (
    CLASS_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS_UNIVERSAL 
(
  ITEM_ID NUMBER(10) NOT NULL 
, CLASS_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_UNIVERSAL_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS_SERVICE 
(
  ITEM_ID NUMBER(10) NOT NULL 
, SERVICE_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_SERVICE_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS_RFC 
(
  ITEM_ID NUMBER(10) NOT NULL 
, RFC_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_RFC_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS_PROBLEM 
(
  ITEM_ID NUMBER(10) NOT NULL 
, PROBLEM_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_PROBLEM_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS_INCIDENT 
(
  ITEM_ID NUMBER(10) NOT NULL 
, INCIDENT_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_INCIDENT_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS_EMPLOYEE 
(
  ITEM_ID NUMBER(10) NOT NULL 
, EMPLOYEE_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_EMPLOYEE_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ITEMS 
(
  ITEM_ID NUMBER(10) NOT NULL 
, CONSTRAINT C2_ITEMS_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE C2_ENTITIES 
(
  ENTITY_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) NOT NULL 
, CONSTRAINT C2_ITEM_BASE_PK PRIMARY KEY 
  (
    ENTITY_ID 
  )
  ENABLE 
);

CREATE TABLE C2_CLASS_ATTRIBUTE_VALUES 
(
  ENTITY_ID NUMBER(10) NOT NULL 
, ATTRIBITE_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) NOT NULL 
, VALUE VARCHAR2(2000) 
, CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_PK PRIMARY KEY 
  (
    ENTITY_ID 
  , ATTRIBITE_ID 
  )
  ENABLE 
);

CREATE TABLE C2_CLASS_ATTRIBUTES 
(
  ATTRIBUTE_ID NUMBER(10) NOT NULL 
, CLASS_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) NOT NULL 
, NAME VARCHAR2(200) NOT NULL 
, DESCRIPTION VARCHAR2(2000) NOT NULL 
, DISPLAY_NO NUMBER(10) NOT NULL 
, CONSTRAINT C2_CLASS_ATTRIBUTES_PK PRIMARY KEY 
  (
    ATTRIBUTE_ID 
  )
  ENABLE 
);

CREATE TABLE C2_CLASSES 
(
  CLASS_ID NUMBER(10) NOT NULL 
, VERSION NUMBER(10) NOT NULL 
, IS_ABSTRACT CHAR(1) NOT NULL 
, NAME VARCHAR2(200) NOT NULL 
, DESCRIPTION VARCHAR2(2000) NOT NULL 
, CONSTRAINT C2_CLASS_DESCRIPTOR_PK PRIMARY KEY 
  (
    CLASS_ID 
  )
  ENABLE 
);

ALTER TABLE C2_CLASSES
ADD CONSTRAINT C2_CLASS_UK1 UNIQUE 
(
  NAME 
)
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASSES_C2_RE_FK1 FOREIGN KEY
(
  PARENT_CLASS_ID 
)
REFERENCES C2_RELATION_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_C2_CLAS_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES C2_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_C2_ITEM_FK1 FOREIGN KEY
(
  SOURCE_CLASS_ID 
)
REFERENCES C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_C2_ITEM_FK2 FOREIGN KEY
(
  TARGET_CLASS_ID 
)
REFERENCES C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_ENTITIES_FK1 FOREIGN KEY
(
  RELATION_ID 
)
REFERENCES C2_ENTITIES
(
  ENTITY_ID 
)
ENABLE;

ALTER TABLE C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_ITEMS_FK1 FOREIGN KEY
(
  SOURCE_ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_ITEMS_FK2 FOREIGN KEY
(
  TARGET_ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_RELATIONS
ADD CONSTRAINT C2_RELATIONS_C2_RELATION__FK1 FOREIGN KEY
(
  RELATION_CLASS_ID 
)
REFERENCES C2_RELATION_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_ITEM_CLASSES
ADD CONSTRAINT C2_ITEM_CLASSES_C2_ITEM_C_FK1 FOREIGN KEY
(
  PARENT_CLASS_ID 
)
REFERENCES C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_ITEM_CLASSES
ADD CONSTRAINT C2_ITEM_CLASS_C2_CLASS_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES C2_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_UNIVERSAL
ADD CONSTRAINT C2_UNIVERSAL_ITEMS_C2_CLA_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES C2_ITEM_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_UNIVERSAL
ADD CONSTRAINT C2_UNIVERSAL_ITEMS_C2_ITE_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_SERVICE
ADD CONSTRAINT C2_SERVICE_ITEMS_C2_ITEMS_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_SERVICE
ADD CONSTRAINT C2_SERVICE_ITEMS_SERVICES_FK1 FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_RFC
ADD CONSTRAINT C2_RFC_ITEMS_C2_ITEMS_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_PROBLEM
ADD CONSTRAINT C2_PROBLEM_ITEMS_C2_ITEMS_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_PROBLEM
ADD CONSTRAINT C2_PROBLEM_ITEMS_INCIDENT_FK1 FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_INCIDENT
ADD CONSTRAINT C2_INCIDENT_ITEMS_C2_ITEM_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_INCIDENT
ADD CONSTRAINT C2_INCIDENT_ITEMS_INCIDEN_FK1 FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_EMPLOYEE
ADD CONSTRAINT C2_EMPLOYEE_ITEMS_C2_ITEM_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ITEMS
(
  ITEM_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS_EMPLOYEE
ADD CONSTRAINT C2_EMPLOYEE_ITEMS_EMPLOYE_FK1 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE C2_ITEMS
ADD CONSTRAINT C2_ITEMS_C2_ENTITIES_FK1 FOREIGN KEY
(
  ITEM_ID 
)
REFERENCES C2_ENTITIES
(
  ENTITY_ID 
)
ENABLE;

ALTER TABLE C2_CLASS_ATTRIBUTE_VALUES
ADD CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_FK1 FOREIGN KEY
(
  ENTITY_ID 
)
REFERENCES C2_ENTITIES
(
  ENTITY_ID 
)
ENABLE;

ALTER TABLE C2_CLASS_ATTRIBUTE_VALUES
ADD CONSTRAINT C2_CLASS_ATTRIBUTE_VALUES_FK2 FOREIGN KEY
(
  ATTRIBITE_ID 
)
REFERENCES C2_CLASS_ATTRIBUTES
(
  ATTRIBUTE_ID 
)
ENABLE;

ALTER TABLE C2_CLASS_ATTRIBUTES
ADD CONSTRAINT C2_CLASS_ATTRIBUTES_C2_CL_FK1 FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES C2_CLASSES
(
  CLASS_ID 
)
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_CHK1 CHECK 
((SOURCE_TYPE = 'ITM' AND SOURCE_CLASS_ID IS NOT NULL) OR (SOURCE_TYPE != 'ITM' AND SOURCE_CLASS_ID IS NULL))
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_CHK2 CHECK 
((TARGET_TYPE = 'ITM' AND TARGET_CLASS_ID IS NOT NULL) OR (TARGET_TYPE != 'ITM' AND TARGET_CLASS_ID IS NULL))
ENABLE;

ALTER TABLE C2_RELATION_CLASSES
ADD CONSTRAINT C2_RELATION_CLASS_CHK3 CHECK 
(QUANTITY IN ('?', '1', '*', '+'))
ENABLE;

ALTER TABLE C2_CLASSES
ADD CONSTRAINT C2_CLASS_CHK1 CHECK 
(IS_ABSTRACT IN ('Y', 'N'))
ENABLE;

CREATE SEQUENCE C2_ENTITIES_SEQ;

CREATE SEQUENCE C2_CLASS_SEQ START WITH 1000;

CREATE SEQUENCE C2_CLASS_ATTRIBUTES_SEQ;
