CREATE OR REPLACE TRIGGER c2_autoinsert_employees
    AFTER INSERT ON employees
    REFERENCING NEW AS employee
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID)
        VALUES (C2_ENTITIES_SEQ.currval);

    INSERT INTO C2_ITEMS_EMPLOYEE (ITEM_ID, EMPLOYEE_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :employee.EMPLOYEE_ID);
END;
/

CREATE OR REPLACE TRIGGER c2_autoinsert_services
    AFTER INSERT ON services
    REFERENCING NEW AS service
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID)
        VALUES (C2_ENTITIES_SEQ.currval);

    INSERT INTO C2_ITEMS_SERVICE (ITEM_ID, SERVICE_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :service.SERVICE_ID);
END;
/

CREATE OR REPLACE TRIGGER c2_autoinsert_incidents
    AFTER INSERT ON incidents
    REFERENCING NEW AS incident
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID)
        VALUES (C2_ENTITIES_SEQ.currval);

    INSERT INTO C2_ITEMS_INCIDENT (ITEM_ID, INCIDENT_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :incident.INCIDENT_ID);
END;
/

CREATE OR REPLACE TRIGGER c2_autoinsert_problems
    AFTER INSERT ON problems
    REFERENCING NEW AS problem
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID)
        VALUES (C2_ENTITIES_SEQ.currval);

    INSERT INTO C2_ITEMS_PROBLEM (ITEM_ID, PROBLEM_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :problem.PROBLEM_ID);
END;
/