CREATE TABLE URGENCY_TYPES_PM 
(
  URGENCY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT URGENCY_TYPES_PM_PK PRIMARY KEY 
  (
    URGENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE URGENCY_TYPES_IM 
(
  URGENCY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT URGENCY_TYPES_PK PRIMARY KEY 
  (
    URGENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SUPPORTING_SERVICES 
(
  SERVICE_ID NUMBER(10) NOT NULL 
, SUPPORTING_SERVICE_ID NUMBER(10) NOT NULL 
, CONSTRAINT SUPPORTING_SERVICES_PK PRIMARY KEY 
  (
    SERVICE_ID 
  , SUPPORTING_SERVICE_ID 
  )
  ENABLE 
);

CREATE TABLE SUPPORT_GROUPS 
(
  GROUP_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(30 BYTE) 
, MANAGER_ID NUMBER(10, 0) 
, CONSTRAINT SUPPORT_GROUPS_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE STATUSES_RF 
(
  STATUS_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT STATUSES_RF_PK PRIMARY KEY 
  (
    STATUS_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE STATUSES_PM 
(
  STATUS_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT STATUSES_PM_PK PRIMARY KEY 
  (
    STATUS_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE STATUSES_IM 
(
  STATUS_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(127 BYTE) 
, CONSTRAINT INCIDENTS_STATUSES_PK PRIMARY KEY 
  (
    STATUS_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SOURCE_TYPES_IM 
(
  SOURCE_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT SOURCE_TYPES_IM_PK PRIMARY KEY 
  (
    SOURCE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SOLUTIONS 
(
  SOLUTION_ID NUMBER(10, 0) NOT NULL 
, PROBLEM_ID NUMBER(10, 0) NOT NULL 
, SOLUTION_CODE CHAR(4 BYTE) NOT NULL 
, SUBJECT VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, AUTHOR NUMBER(10, 0) 
, LAST_UPDATE DATE 
, CONSTRAINT PROBLEM_SOLUTIONS_PK PRIMARY KEY 
  (
    SOLUTION_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SOLUTION_TYPES 
(
  SOLUTION_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT SOLUTION_TYPES_PK PRIMARY KEY 
  (
    SOLUTION_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SOLUTION_CATEGORIES 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) 
, CONSTRAINT SOLUTION_CATEGORIES_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE GLOBAL TEMPORARY TABLE SIGNALS_TMP 
(
  TYPE_CODE NUMBER(10, 0) NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) 
, OBJECT_ID NUMBER(10, 0) 
) 
ON COMMIT DELETE ROWS;

CREATE TABLE SIGNALS 
(
  SIGNAL_ID NUMBER(10, 0) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, IS_SENT CHAR(1 BYTE) DEFAULT 'F' NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, TYPE_CODE NUMBER(10, 0) NOT NULL 
, OBJECT_ID NUMBER(10, 0) NOT NULL 
, ERROR_MESSAGE VARCHAR2(1000) 
, CONSTRAINT SIGNALS_PK PRIMARY KEY 
  (
    SIGNAL_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_TYPES 
(
  TYPE_CODE NUMBER(10, 0) NOT NULL 
, MSG_TEMPLATE VARCHAR2(4000 BYTE) NOT NULL 
, SUBJECT_TEMPLATE VARCHAR2(400 BYTE) NOT NULL 
, SIGNIFICANCE_CODE CHAR(1 BYTE) NOT NULL 
, OBJECT_CODE CHAR(1 BYTE) NOT NULL 
, NAME VARCHAR2(1000 BYTE) 
, CONSTRAINT SIGNAL_TYPES_PK PRIMARY KEY 
  (
    TYPE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_SIGNIFICANCE_TYPES 
(
  SIGNIFICANCE_CODE CHAR(1 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CSS_CLASS VARCHAR2(100 BYTE) 
, CONSTRAINT SIGNAL_SIGNIFICANCE_TYPES_PK PRIMARY KEY 
  (
    SIGNIFICANCE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_RECEIVER_TYPES 
(
  RECEIVER_CODE CHAR(4 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, FROM_STATEMENT VARCHAR2(1000 BYTE) NOT NULL 
, CONSTRAINT SIGNAL_RECEIVER_TYPES_PK PRIMARY KEY 
  (
    RECEIVER_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_OBJECT_TYPES 
(
  OBJECT_CODE CHAR(1 BYTE) NOT NULL 
, VIEW_NAME VARCHAR2(30 BYTE) NOT NULL 
, ID_COLUMN_NAME VARCHAR2(30 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, DETAILS_URL VARCHAR2(100 BYTE) 
, CONSTRAINT SIGNAL_OBJECT_TYPES_PK PRIMARY KEY 
  (
    OBJECT_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_OBJECT_ATTRIBUTE_TYPES 
(
  ATTRIBUTE_CODE CHAR(4 BYTE) NOT NULL 
, ATTRIBUTE_NAME VARCHAR2(30 BYTE) NOT NULL 
, OBJECT_CODE CHAR(1 BYTE) NOT NULL 
, CONSTRAINT SIGNAL_PARAM_TYPES_PK PRIMARY KEY 
  (
    ATTRIBUTE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_GENERATORS 
(
  GENERATOR_ID NUMBER(8, 0) NOT NULL 
, TYPE_CODE NUMBER(10, 0) NOT NULL 
, CRITERION VARCHAR2(1000 BYTE) NOT NULL 
, SELECT_STATEMENT VARCHAR2(1000 BYTE) NOT NULL 
, RECEIVER_CODE CHAR(4 BYTE) NOT NULL 
, ENABLED CHAR(1 BYTE) NOT NULL 
, FREQUENCY NUMBER(3, 0) NOT NULL 
, LAST_RUN_STATUS CHAR(1 BYTE) 
, LAST_RUN_DATE DATE 
, ERROR_MESSAGE VARCHAR2(1000) 
, CONSTRAINT SIGNAL_GENERATORS_PK PRIMARY KEY 
  (
    GENERATOR_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIGNAL_ATTRIBUTES 
(
  ATTRIBUTE_ID NUMBER(11, 0) NOT NULL 
, SIGNAL_ID NUMBER(10, 0) NOT NULL 
, ATTRIBUTE_CODE CHAR(4 BYTE) NOT NULL 
, ATTRIBUTE_VALUE VARCHAR2(1000 BYTE) 
, CONSTRAINT SIGNAL_PARAMS_PK PRIMARY KEY 
  (
    ATTRIBUTE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SERVICES 
(
  SERVICE_ID NUMBER(10) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, DESCRIPTION VARCHAR2(1000) NOT NULL 
, SERVICE_TYPE_CODE CHAR(4) NOT NULL 
, BUSINESS_IMPACT_CODE CHAR(4) NOT NULL 
, BUSINESS_PRIORITY_CODE CHAR(4) NOT NULL 
, AGREEMENT_ID NUMBER(10) NOT NULL 
, CONSTRAINT SERVICES_PK PRIMARY KEY 
  (
    SERVICE_ID 
  )
  ENABLE 
);

CREATE TABLE SERVICE_TYPES 
(
  SERVICE_TYPE_CODE CHAR(4) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, CONSTRAINT SERVICE_TYPES_PK PRIMARY KEY 
  (
    SERVICE_TYPE_CODE 
  )
  ENABLE 
);

CREATE TABLE SERVICE_MANAGERS 
(
  SERVICE_ID NUMBER(10) NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT SERVICE_MANAGERS_PK PRIMARY KEY 
  (
    SERVICE_ID 
  , EMPLOYEE_ID 
  )
  ENABLE 
);

CREATE TABLE ROLES 
(
  ROLE_CODE VARCHAR2(10 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT ROLES_PK PRIMARY KEY 
  (
    ROLE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ROLE_PRIVILEGE 
(
  ROLE_CODE VARCHAR2(10 BYTE) NOT NULL 
, PRIVILEGE_CODE VARCHAR2(10 BYTE) NOT NULL 
, CONSTRAINT ROLE_PRIVILEGE_PK PRIMARY KEY 
  (
    ROLE_CODE 
  , PRIVILEGE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE REQUESTS 
(
  REQUEST_ID NUMBER(10, 0) NOT NULL 
, PRIORITY_CODE CHAR(4 BYTE) 
, STATUS_CODE CHAR(4 BYTE) DEFAULT 'OPEN' NOT NULL 
, CREATION_DATE DATE 
, AUTHOR NUMBER(10, 0) 
, CATEGORY_CODE CHAR(4 BYTE) 
, EMPLOYEE_ID NUMBER(10, 0) 
, CLOSURE_DATE DATE 
, TARGET_RESOLUTION_DATE DATE 
, STAFF_MEMBER NUMBER(10, 0) 
, GROUP_ID NUMBER(10, 0) 
, CONSTRAINT REQUESTS_PK PRIMARY KEY 
  (
    REQUEST_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE REQUEST_ATTRIBUTES 
(
  ATTRIBUTE_ID NUMBER(10, 0) NOT NULL 
, REQUEST_ID NUMBER(10, 0) 
, TYPE_CODE CHAR(6 BYTE) 
, VALUE VARCHAR2(1000 BYTE) 
, CONSTRAINT REQUEST_ATTRIBUTES_PK PRIMARY KEY 
  (
    ATTRIBUTE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE REQUEST_ATTRIBUTE_TYPES 
(
  TYPE_CODE CHAR(6 BYTE) NOT NULL 
, REQUIRED CHAR(1 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, INPUT_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT REQUEST_ATTRIBUTE_TYPES_PK PRIMARY KEY 
  (
    TYPE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PROBLEMS 
(
  PROBLEM_ID NUMBER(10, 0) NOT NULL 
, IS_KNOWN_ERROR CHAR(1 BYTE) DEFAULT 'f' NOT NULL 
, SUBJECT VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, CLOSURE_DATE DATE 
, STATUS_CODE CHAR(4 BYTE) DEFAULT 'OPEN' NOT NULL 
, IMPACT_CODE CHAR(4 BYTE) 
, URGENCY_CODE CHAR(4 BYTE) 
, IMPACT_DETAILS VARCHAR2(1000 BYTE) 
, ROOT_CAUSE VARCHAR2(1000 BYTE) 
, SYMPTOMS VARCHAR2(1000 BYTE) 
, AUTHOR NUMBER(10, 0) NOT NULL 
, PRIORITY_CODE CHAR(4 BYTE) 
, STAFF_MEMBER NUMBER(10, 0) 
, GROUP_ID NUMBER(10, 0) 
, CONSTRAINT PROBLEMS_PK PRIMARY KEY 
  (
    PROBLEM_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PRIVILEGE_TYPES 
(
  PRIVILEGE_CODE VARCHAR2(10 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT PRIVILEGE_TYPES_PK PRIMARY KEY 
  (
    PRIVILEGE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PRIORITY_TYPES_RF 
(
  PRIORITY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, TARGET_RESOLUTION_TIME NUMBER(2, 0) 
, CONSTRAINT PRIORITY_TYPES_RF_PK PRIMARY KEY 
  (
    PRIORITY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PRIORITY_TYPES_PM 
(
  PRIORITY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT PRIORITY_TYPES_PM_PK PRIMARY KEY 
  (
    PRIORITY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PRIORITY_TYPES_IM 
(
  PRIORITY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, TARGET_RESOLUTION_TIME NUMBER(2, 0) NOT NULL 
, CONSTRAINT PRIORITY_TYPES_PK PRIMARY KEY 
  (
    PRIORITY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE JOBS 
(
  JOB_CODE VARCHAR2(10 BYTE) NOT NULL 
, JOB_TITLE VARCHAR2(35 BYTE) NOT NULL 
, CONSTRAINT JOB_ID_PK PRIMARY KEY 
  (
    JOB_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE INCIDENTS_HISTORY 
(
  HISTORY_ID NUMBER(12, 0) NOT NULL 
, CHANGE_DATE DATE NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, INCIDENT_ID NUMBER(10, 0) NOT NULL 
, IMPACT_CODE CHAR(4 BYTE) 
, URGENCY_CODE CHAR(4 BYTE) 
, STATUS_CODE CHAR(4 BYTE) 
, REVIEW VARCHAR2(1024 BYTE) 
, PRIORITY_CODE CHAR(4 BYTE) 
, CATEGORY_CODE CHAR(4 BYTE) 
, SUBJECT VARCHAR2(100 BYTE) 
, DESCRIPTION VARCHAR2(4000 BYTE) 
, STAFF_MEMBER NUMBER(10, 0) 
, RESOLUTION VARCHAR2(4000 BYTE) 
, SOURCE_CODE CHAR(4 BYTE) 
, RESOLUTION_DATE DATE 
, GROUP_ID NUMBER(10, 0) 
, TARGET_RESOLUTION_DATE DATE 
, CLOSURE_DATE DATE 
, SERVICE_ID NUMBER(10) 
, CONSTRAINT INCIDENTS_HISTORY_PK PRIMARY KEY 
  (
    HISTORY_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE INCIDENTS 
(
  INCIDENT_ID NUMBER(10, 0) NOT NULL 
, IMPACT_CODE CHAR(4 BYTE) 
, URGENCY_CODE CHAR(4 BYTE) 
, STATUS_CODE CHAR(4 BYTE) DEFAULT 'OPEN' NOT NULL 
, REVIEW VARCHAR2(1024 BYTE) 
, PRIORITY_CODE CHAR(4 BYTE) 
, AUTHOR NUMBER(10, 0) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, CLOSURE_DATE DATE 
, SUBJECT VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, STAFF_MEMBER NUMBER(10, 0) 
, RESOLUTION VARCHAR2(4000 BYTE) 
, SOURCE_CODE CHAR(4 BYTE) 
, RESOLUTION_DATE DATE 
, GROUP_ID NUMBER(10, 0) 
, TARGET_RESOLUTION_DATE DATE 
, SERVICE_ID NUMBER(10) 
, LAST_EDIT_BY NUMBER(10, 0) DEFAULT 0 
, CONSTRAINT INCIDENTS_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE INCIDENT_PROBLEM 
(
  INCIDENT_ID NUMBER(10, 0) NOT NULL 
, PROBLEM_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT INCIDENT_PROBLEM_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  , PROBLEM_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE IMPACT_URGENCY_IM 
(
  IMPACT_CODE CHAR(4 BYTE) NOT NULL 
, URGENCY_CODE CHAR(4 BYTE) NOT NULL 
, PRIORITY_CODE CHAR(4 BYTE) 
, CONSTRAINT IMPACT_URGENCY_PK PRIMARY KEY 
  (
    IMPACT_CODE 
  , URGENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE IMPACT_TYPES_PM 
(
  IMPACT_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT IMPACT_TYPES_PM_PK PRIMARY KEY 
  (
    IMPACT_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE IMPACT_TYPES_IM 
(
  IMPACT_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT IMPACT_TYPES_PK PRIMARY KEY 
  (
    IMPACT_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE GROUP_MEMBER 
(
  GROUP_ID NUMBER(10, 0) NOT NULL 
, EMPLOYEE_ID NUMBER(10, 0) 
, CONSTRAINT GROUP_MEMBER_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EVENTS 
(
  EVENT_ID NUMBER(10, 0) NOT NULL 
, SIGNIFICANCE_CODE CHAR(4 BYTE) NOT NULL 
, EVENT_DATE DATE NOT NULL 
, CREATION_DATE DATE NOT NULL 
, SUBJECT VARCHAR2(1000 BYTE) NOT NULL 
, CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, INCIDENT_ID NUMBER(10, 0) 
, CONSTRAINT EVENTS_PK PRIMARY KEY 
  (
    EVENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EVENT_SIGNIFICANCE_TYPES 
(
  SIGNIFICANCE_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT EVENT_TYPES_PK PRIMARY KEY 
  (
    SIGNIFICANCE_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EVENT_PARAMETERS 
(
  PARAMETER_ID NUMBER(10, 0) NOT NULL 
, EVENT_ID NUMBER(10, 0) NOT NULL 
, PARAM_NAME VARCHAR2(200 BYTE) NOT NULL 
, PARAM_VALUE VARCHAR2(4000 BYTE) NOT NULL 
, CONSTRAINT EVENT_PARAMETERS_PK PRIMARY KEY 
  (
    PARAMETER_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EVENT_INCIDENT 
(
  EVENT_ID NUMBER(10, 0) NOT NULL 
, INCIDENT_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT EVENT_INCIDENT_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  , EVENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EMPLOYEES 
(
  EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
, SURNAME VARCHAR2(30 BYTE) NOT NULL 
, PHONE_NUMBER VARCHAR2(20 BYTE) NOT NULL 
, MOBILE_PHONE VARCHAR2(20 BYTE) 
, EMAIL VARCHAR2(30 BYTE) NOT NULL 
, LOGIN VARCHAR2(10 BYTE) NOT NULL 
, PASSWORD VARCHAR2(100 BYTE) NOT NULL 
, ENABLED NUMBER(1, 0) NOT NULL 
, MANAGER_ID NUMBER(10, 0) 
, DEPARTMENT_ID NUMBER(4, 0) 
, JOB_CODE VARCHAR2(10 BYTE) 
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EMPLOYEE_SERVICE 
(
  EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, SERVICE_ID NUMBER(10) NOT NULL 
, AGREEMENT_ID NUMBER(10) 
, CONSTRAINT EMPLOYEE_SERVICE_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  , SERVICE_ID 
  )
  ENABLE 
);

CREATE TABLE EMPLOYEE_ROLE 
(
  EMPLOYEE_ID NUMBER(10, 0) NOT NULL 
, ROLE_CODE VARCHAR2(10 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE DEPARTMENTS 
(
  DEPARTMENT_ID NUMBER(4, 0) NOT NULL 
, DEPARTMENT_NAME VARCHAR2(30 BYTE) NOT NULL 
, MANAGER_ID NUMBER(10, 0) 
, CONSTRAINT DEPT_ID_PK PRIMARY KEY 
  (
    DEPARTMENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE COMMENTS 
(
  COMMENT_ID NUMBER(10, 0) NOT NULL 
, TEXT VARCHAR2(4000 BYTE) 
, CREATION_DATE DATE DEFAULT sysdate NOT NULL 
, EVENT_ID NUMBER(10, 0) 
, EMPLOYEE_ID NUMBER(10, 0) 
, PROBLEM_ID NUMBER(10, 0) 
, INCIDENT_ID NUMBER(10, 0) 
, REQUEST_ID NUMBER(10, 0) 
, CONSTRAINT PROBLEM_COMMENTS_PK PRIMARY KEY 
  (
    COMMENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE CATEGORIES_RF 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, CONSTRAINT CATEGORIES_RF_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE CATEGORIES_PM 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, GROUP_ID NUMBER(10, 0) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, CONSTRAINT CATEGORIES_PM_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE CATEGORIES_IM 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(50 BYTE) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, GROUP_ID NUMBER(10, 0) 
, CONSTRAINT INCIDENT_CATEGORY_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE CATEGORIES_EM 
(
  CATEGORY_CODE CHAR(4 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, PARENT_CATEGORY CHAR(4 BYTE) 
, CONSTRAINT EVENT_CATEGORIES_PK PRIMARY KEY 
  (
    CATEGORY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ATTACHMENTS 
(
  ATTACHMENT_ID NUMBER(10, 0) NOT NULL 
, EVENT_ID NUMBER(12, 0) NOT NULL 
, BYTES BLOB NOT NULL 
, CONSTRAINT ATTACHMENTS_TMP_PK PRIMARY KEY 
  (
    ATTACHMENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (BYTES) STORE AS SYS_LOB0000017138C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE AGREEMENTS 
(
  AGREEMENT_ID NUMBER(10) NOT NULL 
, START_HOUR NUMBER(2) NOT NULL 
, END_HOUR NUMBER(2) NOT NULL 
, RESOLUTION_TIME NUMBER(2) NOT NULL 
, AVAILABILITY NUMBER(4, 2) 
, CONSTRAINT SLA_PK PRIMARY KEY 
  (
    AGREEMENT_ID 
  )
  ENABLE 
);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_LOGIN_UK UNIQUE 
(
  LOGIN 
)
ENABLE;

ALTER TABLE SUPPORTING_SERVICES
ADD CONSTRAINT SUPPORTING_SERVICES_SERVI_FK1 FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SUPPORTING_SERVICES
ADD CONSTRAINT SUPPORTING_SERVICES_SERVI_FK2 FOREIGN KEY
(
  SUPPORTING_SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE SOLUTIONS
ADD CONSTRAINT PROBLEM_SOLUTIONS_PROBLEM_FK1 FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE SOLUTIONS
ADD CONSTRAINT PROBLEM_SOLUTIONS_SOLUTIO_FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES SOLUTION_CATEGORIES
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SOLUTIONS
ADD CONSTRAINT SOLUTIONS_EMPLOYEES_FK FOREIGN KEY
(
  AUTHOR 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SOLUTIONS
ADD CONSTRAINT SOLUTIONS_SOLUTION_TYPES_FK FOREIGN KEY
(
  SOLUTION_CODE 
)
REFERENCES SOLUTION_TYPES
(
  SOLUTION_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_TYPES
ADD CONSTRAINT SIGNAL_TYPES_SIGNAL_OBJEC_FK1 FOREIGN KEY
(
  OBJECT_CODE 
)
REFERENCES SIGNAL_OBJECT_TYPES
(
  OBJECT_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_TYPES
ADD CONSTRAINT SIGNAL_TYPES_SIGNAL_SIGNI_FK FOREIGN KEY
(
  SIGNIFICANCE_CODE 
)
REFERENCES SIGNAL_SIGNIFICANCE_TYPES
(
  SIGNIFICANCE_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_OBJECT_ATTRIBUTE_TYPES
ADD CONSTRAINT SIGNAL_OBJECT_ATTRIBUTE_TYP_FK FOREIGN KEY
(
  OBJECT_CODE 
)
REFERENCES SIGNAL_OBJECT_TYPES
(
  OBJECT_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GENERATORS_RECEIVER_FK FOREIGN KEY
(
  RECEIVER_CODE 
)
REFERENCES SIGNAL_RECEIVER_TYPES
(
  RECEIVER_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GENERATORS_SIGNAL_FK FOREIGN KEY
(
  TYPE_CODE 
)
REFERENCES SIGNAL_TYPES
(
  TYPE_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_ATTRIBUTES
ADD CONSTRAINT SIGNAL_ATTRIBUTES_SIGNAL__FK1 FOREIGN KEY
(
  ATTRIBUTE_CODE 
)
REFERENCES SIGNAL_OBJECT_ATTRIBUTE_TYPES
(
  ATTRIBUTE_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_ATTRIBUTES
ADD CONSTRAINT SIGNAL_PARAMS_SIGNALS_FK FOREIGN KEY
(
  SIGNAL_ID 
)
REFERENCES SIGNALS
(
  SIGNAL_ID 
)
ENABLE;

ALTER TABLE SERVICES
ADD CONSTRAINT SERVICES_SERVICE_TYPES_FK FOREIGN KEY
(
  SERVICE_TYPE_CODE 
)
REFERENCES SERVICE_TYPES
(
  SERVICE_TYPE_CODE 
)
ENABLE;

ALTER TABLE SERVICES
ADD CONSTRAINT SERVICES_SLA_FK FOREIGN KEY
(
  AGREEMENT_ID 
)
REFERENCES AGREEMENTS
(
  AGREEMENT_ID 
)
ENABLE;

ALTER TABLE SERVICE_MANAGERS
ADD CONSTRAINT SERVICE_MANAGERS_EMPLOYEE_FK1 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE SERVICE_MANAGERS
ADD CONSTRAINT SERVICE_MANAGERS_SERVICES_FK FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE ROLE_PRIVILEGE
ADD CONSTRAINT ROLE_PRIVILEGE_PRIVILEGE__FK1 FOREIGN KEY
(
  PRIVILEGE_CODE 
)
REFERENCES PRIVILEGE_TYPES
(
  PRIVILEGE_CODE 
)
ENABLE;

ALTER TABLE ROLE_PRIVILEGE
ADD CONSTRAINT ROLE_PRIVILEGE_ROLES_FK FOREIGN KEY
(
  ROLE_CODE 
)
REFERENCES ROLES
(
  ROLE_CODE 
)
ENABLE;

ALTER TABLE REQUESTS
ADD CONSTRAINT REQUESTS_CATEGORIES_RF_FK FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES CATEGORIES_RF
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE REQUESTS
ADD CONSTRAINT REQUESTS_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE REQUESTS
ADD CONSTRAINT REQUESTS_EMPLOYEES_FK1 FOREIGN KEY
(
  STAFF_MEMBER 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE REQUESTS
ADD CONSTRAINT REQUESTS_PRIORITY_TYPES_R_FK1 FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES PRIORITY_TYPES_RF
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE REQUESTS
ADD CONSTRAINT REQUESTS_STATUSES_RF_FK FOREIGN KEY
(
  STATUS_CODE 
)
REFERENCES STATUSES_RF
(
  STATUS_CODE 
)
ENABLE;

ALTER TABLE REQUESTS
ADD CONSTRAINT REQUESTS_SUPPORT_GROUPS_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE REQUEST_ATTRIBUTES
ADD CONSTRAINT REQUEST_ATTRIBUTES_REQUES_FK1 FOREIGN KEY
(
  TYPE_CODE 
)
REFERENCES REQUEST_ATTRIBUTE_TYPES
(
  TYPE_CODE 
)
ENABLE;

ALTER TABLE REQUEST_ATTRIBUTES
ADD CONSTRAINT REQ_ATT_REQ_FK FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES REQUESTS
(
  REQUEST_ID 
)
ENABLE;

ALTER TABLE REQUEST_ATTRIBUTE_TYPES
ADD CONSTRAINT REQUEST_ATTRIBUTE_TYPES_C_FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES CATEGORIES_RF
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_CATEGORIES_PM_FK FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES CATEGORIES_PM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_EMPLOYEES_FK FOREIGN KEY
(
  AUTHOR 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_EMPLOYEES_FK1 FOREIGN KEY
(
  STAFF_MEMBER 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_IMPACT_TYPES_PM_FK FOREIGN KEY
(
  IMPACT_CODE 
)
REFERENCES IMPACT_TYPES_PM
(
  IMPACT_CODE 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_PRIORITY_TYPES_P_FK1 FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES PRIORITY_TYPES_PM
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_STATUSES_PM_FK FOREIGN KEY
(
  STATUS_CODE 
)
REFERENCES STATUSES_PM
(
  STATUS_CODE 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_SUPPORT_GROUPS_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE PROBLEMS
ADD CONSTRAINT PROBLEMS_URGENCY_TYPES_PM_FK FOREIGN KEY
(
  URGENCY_CODE 
)
REFERENCES URGENCY_TYPES_PM
(
  URGENCY_CODE 
)
ENABLE;

ALTER TABLE INCIDENTS_HISTORY
ADD CONSTRAINT INCIDENTS_HISTORY_INCIDEN_FK1 FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_EMPLOYEES_FK FOREIGN KEY
(
  AUTHOR 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_EMPLOYEES_FK1 FOREIGN KEY
(
  STAFF_MEMBER 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_EMPLOYEES_FK2 FOREIGN KEY
(
  LAST_EDIT_BY 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_IMPACT_TYPES_FK FOREIGN KEY
(
  IMPACT_CODE 
)
REFERENCES IMPACT_TYPES_IM
(
  IMPACT_CODE 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_INCIDENT_CATEGO_FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES CATEGORIES_IM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_PRIORITY_TYPES_FK FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES PRIORITY_TYPES_IM
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_SERVICES_FK FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_SOURCE_TYPES_IM_FK FOREIGN KEY
(
  SOURCE_CODE 
)
REFERENCES SOURCE_TYPES_IM
(
  SOURCE_CODE 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_STATUSES_IM_FK FOREIGN KEY
(
  STATUS_CODE 
)
REFERENCES STATUSES_IM
(
  STATUS_CODE 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_SUPPORT_GROUPS_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE INCIDENTS
ADD CONSTRAINT INCIDENTS_URGENCY_TYPES_FK FOREIGN KEY
(
  URGENCY_CODE 
)
REFERENCES URGENCY_TYPES_IM
(
  URGENCY_CODE 
)
ENABLE;

ALTER TABLE INCIDENT_PROBLEM
ADD CONSTRAINT INCIDENT_PROBLEM_INCIDENT_FK1 FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE INCIDENT_PROBLEM
ADD CONSTRAINT INCIDENT_PROBLEM_PROBLEMS_FK FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE IMPACT_URGENCY_IM
ADD CONSTRAINT IMPACT_URGENCY_IMPACT_TYP_FK1 FOREIGN KEY
(
  IMPACT_CODE 
)
REFERENCES IMPACT_TYPES_IM
(
  IMPACT_CODE 
)
ENABLE;

ALTER TABLE IMPACT_URGENCY_IM
ADD CONSTRAINT IMPACT_URGENCY_PRIORITY_T_FK1 FOREIGN KEY
(
  PRIORITY_CODE 
)
REFERENCES PRIORITY_TYPES_IM
(
  PRIORITY_CODE 
)
ENABLE;

ALTER TABLE IMPACT_URGENCY_IM
ADD CONSTRAINT IMPACT_URGENCY_URGENCY_TY_FK1 FOREIGN KEY
(
  URGENCY_CODE 
)
REFERENCES URGENCY_TYPES_IM
(
  URGENCY_CODE 
)
ENABLE;

ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT GROUP_MEMBER_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT GROUP_MEMBER_SUPPORT_GROU_FK1 FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES SUPPORT_GROUPS
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE EVENTS
ADD CONSTRAINT EVENTS_EVENT_CATEGORIES_FK FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES CATEGORIES_EM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE EVENTS
ADD CONSTRAINT EVENTS_EVENT_SIGNIFICANCE_FK1 FOREIGN KEY
(
  SIGNIFICANCE_CODE 
)
REFERENCES EVENT_SIGNIFICANCE_TYPES
(
  SIGNIFICANCE_CODE 
)
ENABLE;

ALTER TABLE EVENTS
ADD CONSTRAINT EVENTS_INCIDENTS_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE EVENT_PARAMETERS
ADD CONSTRAINT EVENT_PARAMETERS_EVENTS_FK FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES EVENTS
(
  EVENT_ID 
)
ENABLE;

ALTER TABLE EVENT_INCIDENT
ADD CONSTRAINT EVENT_INCIDENT_EVENTS_FK FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES EVENTS
(
  EVENT_ID 
)
ENABLE;

ALTER TABLE EVENT_INCIDENT
ADD CONSTRAINT EVENT_INCIDENT_INCIDENTS_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_DEPARTMENTS_FK FOREIGN KEY
(
  DEPARTMENT_ID 
)
REFERENCES DEPARTMENTS
(
  DEPARTMENT_ID 
)
ENABLE;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_EMPLOYEES_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_JOBS_FK FOREIGN KEY
(
  JOB_CODE 
)
REFERENCES JOBS
(
  JOB_CODE 
)
ENABLE;

ALTER TABLE EMPLOYEE_SERVICE
ADD CONSTRAINT EMPLOYEE_SERVICE_AGREEMEN_FK1 FOREIGN KEY
(
  AGREEMENT_ID 
)
REFERENCES AGREEMENTS
(
  AGREEMENT_ID 
)
ENABLE;

ALTER TABLE EMPLOYEE_SERVICE
ADD CONSTRAINT EMPLOYEE_SERVICE_EMPLOYEE_FK1 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE EMPLOYEE_SERVICE
ADD CONSTRAINT EMPLOYEE_SERVICE_SERVICES_FK FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE EMPLOYEE_ROLE
ADD CONSTRAINT EMPLOYEE_ROLE_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE EMPLOYEE_ROLE
ADD CONSTRAINT EMPLOYEE_ROLE_ROLES_FK FOREIGN KEY
(
  ROLE_CODE 
)
REFERENCES ROLES
(
  ROLE_CODE 
)
ENABLE;

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPARTMENTS_EMPLOYEES_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_EMPLOYEES_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_INCIDENTS_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES INCIDENTS
(
  INCIDENT_ID 
)
ENABLE;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_PROBLEMS_FK FOREIGN KEY
(
  PROBLEM_ID 
)
REFERENCES PROBLEMS
(
  PROBLEM_ID 
)
ENABLE;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_REQUESTS_FK FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES REQUESTS
(
  REQUEST_ID 
)
ENABLE;

ALTER TABLE CATEGORIES_RF
ADD CONSTRAINT CATEGORIES_RF_CATEGORIES__FK1 FOREIGN KEY
(
  PARENT_CATEGORY 
)
REFERENCES CATEGORIES_RF
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE CATEGORIES_PM
ADD CONSTRAINT CATEGORIES_PM_CATEGORIES__FK1 FOREIGN KEY
(
  CATEGORY_CODE 
)
REFERENCES CATEGORIES_PM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE CATEGORIES_IM
ADD CONSTRAINT INCIDENT_CATEGORY_INCIDEN_FK1 FOREIGN KEY
(
  PARENT_CATEGORY 
)
REFERENCES CATEGORIES_IM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE CATEGORIES_EM
ADD CONSTRAINT EVENT_CATEGORIES_EVENT_CA_FK1 FOREIGN KEY
(
  PARENT_CATEGORY 
)
REFERENCES CATEGORIES_EM
(
  CATEGORY_CODE 
)
ENABLE;

ALTER TABLE SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GEN_ENABLED_CHK CHECK 
(ENABLED IN ('T', 'F'))
ENABLE;

ALTER TABLE SIGNAL_GENERATORS
ADD CONSTRAINT SIGNAL_GEN_STATUS_CHK CHECK 
(LAST_RUN_STATUS IN ('T', 'F'))
ENABLE;

ALTER TABLE REQUEST_ATTRIBUTE_TYPES
ADD CONSTRAINT REQ_ATTR_REQUIRED_CHK CHECK 
(REQUIRED IN ('t', 'f'))
ENABLE;

ALTER TABLE JOBS
ADD CONSTRAINT JOB_TITLE_NN CHECK 
(JOB_TITLE IS NOT NULL)
ENABLE;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_ENABLED_CHK CHECK 
(ENABLED IN (1, 0))
ENABLE;

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPT_NAME_NN CHECK 
(DEPARTMENT_NAME IS NOT NULL)
ENABLE;

CREATE VIEW USERS AS SELECT
login as username
, password
, enabled
FROM employees;

CREATE VIEW CATEGORIES_PM_V AS select
  c1.name as main_category, null as sub_category, null as sub_sub_category, category_code, name
from
  categories_pm c1
where
  c1.parent_category is null
union all
select
  c2.name as main_category, c1.name as sub_category, null as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
where
  c2.parent_category is null
union all
select
  c3.name as main_category, c2.name as sub_category, c1.name as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
  join categories_pm c3 on c2.parent_category = c3.category_code
where
  c3.parent_category is null
union all
select
  c4.name as main_category, c3.name as sub_category, c2.name as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
  join categories_pm c3 on c2.parent_category = c3.category_code
  join categories_pm c4 on c3.parent_category = c4.category_code
where
  c4.parent_category is null 
union all
select
  c5.name as main_category, c4.name as sub_category, c3.name as sub_sub_category, c1.category_code, c1.name
from
  categories_pm c1
  join categories_pm c2 on c1.parent_category = c2.category_code
  join categories_pm c3 on c2.parent_category = c3.category_code
  join categories_pm c4 on c3.parent_category = c4.category_code
  join categories_pm c5 on c4.parent_category = c3.category_code
where
  c5.parent_category is null;

CREATE VIEW CATEGORIES_IM_V AS select
  c1.name as main_category, null as sub_category, null as sub_sub_category, category_code, name
from
  categories_im c1
where
  c1.parent_category is null
union all
select
  c2.name as main_category, c1.name as sub_category, null as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
where
  c2.parent_category is null
union all
select
  c3.name as main_category, c2.name as sub_category, c1.name as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
  join categories_im c3 on c2.parent_category = c3.category_code
where
  c3.parent_category is null
union all
select
  c4.name as main_category, c3.name as sub_category, c2.name as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
  join categories_im c3 on c2.parent_category = c3.category_code
  join categories_im c4 on c3.parent_category = c4.category_code
where
  c4.parent_category is null 
union all
select
  c5.name as main_category, c4.name as sub_category, c3.name as sub_sub_category, c1.category_code, c1.name
from
  categories_im c1
  join categories_im c2 on c1.parent_category = c2.category_code
  join categories_im c3 on c2.parent_category = c3.category_code
  join categories_im c4 on c3.parent_category = c4.category_code
  join categories_im c5 on c4.parent_category = c3.category_code
where
  c5.parent_category is null;

CREATE VIEW CATEGORIES_EM_V AS SELECT c1.name AS main_category,
    NULL         AS sub_category,
    NULL         AS sub_sub_category,
    category_code,
    name
  FROM categories_em c1
  WHERE c1.parent_category IS NULL
  UNION ALL
  SELECT c2.name AS main_category,
    c1.name      AS sub_category,
    NULL         AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category     = c2.category_code
  WHERE c2.parent_category IS NULL
  UNION ALL
  SELECT c3.name AS main_category,
    c2.name      AS sub_category,
    c1.name      AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category = c2.category_code
  JOIN categories_em c3
  ON c2.parent_category     = c3.category_code
  WHERE c3.parent_category IS NULL
  UNION ALL
  SELECT c4.name AS main_category,
    c3.name      AS sub_category,
    c2.name      AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category = c2.category_code
  JOIN categories_em c3
  ON c2.parent_category = c3.category_code
  JOIN categories_em c4
  ON c3.parent_category     = c4.category_code
  WHERE c4.parent_category IS NULL
  UNION ALL
  SELECT c5.name AS main_category,
    c4.name      AS sub_category,
    c3.name      AS sub_sub_category,
    c1.category_code,
    c1.name
  FROM categories_em c1
  JOIN categories_em c2
  ON c1.parent_category = c2.category_code
  JOIN categories_em c3
  ON c2.parent_category = c3.category_code
  JOIN categories_em c4
  ON c3.parent_category = c4.category_code
  JOIN categories_em c5
  ON c4.parent_category     = c3.category_code
  WHERE c5.parent_category IS NULL;

CREATE VIEW PROBLEMS_V AS select
  i.problem_id
  , i.subject
  , i.creation_date
  , extract(year from i.creation_date) as creation_year
  ,  'Q' || to_char(i.creation_date, 'Q ') as creation_quarter
  , extract(month from i.creation_date) as creation_month
  , extract(day from i.creation_date) as creation_day
  , to_char(i.creation_date, 'month') as creation_month_name
  , c.main_category
  , c.sub_category
  , c.sub_sub_category 
  , c.name as category
  , c.category_code
  , i.closure_date
  , extract(year from i.closure_date) as closure_year
  , extract(month from i.closure_date) as closure_month
  , extract(day from i.closure_date) as closure_day
  , to_char(i.closure_date, 'month') as closure_month_name
  , p.name as priority
  , p.priority_code
  , s.name as status
  , s.status_code
  , coalesce(e_gr.name || ' ' || e_gr.surname, 'BRAK') as staff_member
  , e_gr.employee_id as staff_member_id
  , coalesce(gr.name, 'BRAK') as support_group
  , gr.group_id
from
  problems i
  left join categories_pm_v c on i.category_code = c.category_code
  left join priority_types_pm p on p.priority_code = i.priority_code
  left join statuses_pm s on s.status_code = i.status_code
  left join employees e_gr on e_gr.employee_id = i.staff_member
  left join support_groups gr on gr.group_id = i.group_id;

CREATE VIEW KNOWN_ERRORS_V AS select p.problem_id, p.subject as subject, p.symptoms, p.root_cause, s.description as workaround, p.category_code
from solutions s join problems p on p.problem_id = s.problem_id
where p.is_known_error = 'T';

CREATE VIEW INCIDENTS_V AS SELECT i.incident_id ,
    i.subject ,
    i.creation_date ,
    extract(DAY FROM i.creation_date)   AS creation_day ,
    extract(YEAR FROM i.creation_date)  AS creation_year ,
    extract(MONTH FROM i.creation_date) AS creation_month ,
    'Q'
    || TO_CHAR(i.creation_date, 'Q ') AS creation_quarter ,
    TO_CHAR(i.creation_date, 'month') AS creation_month_name ,
    c.main_category ,
    c.sub_category ,
    c.sub_sub_category ,
    c.name AS category ,
    c.category_code,
    i.closure_date ,
    extract(YEAR FROM i.closure_date)  AS closure_year ,
    extract(MONTH FROM i.closure_date) AS closure_month ,
    extract(DAY FROM i.closure_date)   AS closure_day ,
    TO_CHAR(i.closure_date, 'month')   AS closure_month_name ,
    i.resolution_date ,
    extract(YEAR FROM i.resolution_date)  AS resolution_year ,
    extract(MONTH FROM i.resolution_date) AS resolution_month ,
    extract(DAY FROM i.resolution_date)   AS resolution_day ,
    TO_CHAR(i.resolution_date, 'month')   AS resolution_month_name ,
    i.target_resolution_date,
    COALESCE(p.name, 'NULL')              AS priority ,
    p.priority_code,
    COALESCE(s.name, 'NULL')              AS status ,
    s.status_code,
    COALESCE(sot.name, 'NULL')            AS source ,
    sot.source_code,
    COALESCE(e_gr.name
    || ' '
    || e_gr.surname, 'BRAK')  AS staff_member ,
    e_gr.employee_id as staff_member_id,
    COALESCE(gr.name, 'BRAK') AS support_group ,
    gr.group_id,
    i.author
  FROM incidents i
  LEFT JOIN categories_im_v c
  ON i.category_code = c.category_code
  LEFT JOIN priority_types_im p
  ON p.priority_code = i.priority_code
  LEFT JOIN statuses_im s
  ON s.status_code = i.status_code
  LEFT JOIN source_types_im sot
  ON sot.source_code = i.source_code
  LEFT JOIN employees e_gr
  ON e_gr.employee_id = i.staff_member
  LEFT JOIN support_groups gr
  ON gr.group_id = i.group_id;

CREATE VIEW EVENTS_V AS SELECT e.event_id,
    e.subject ,
    e.creation_date ,
    extract(YEAR FROM e.creation_date)  AS creation_year ,
    extract(MONTH FROM e.creation_date) AS creation_month ,
    TO_CHAR(e.creation_date, 'month')   AS creation_month_name ,
    e.event_date ,
    extract(YEAR FROM e.event_date)  AS event_year ,
    extract(MONTH FROM e.event_date) AS event_month ,
    TO_CHAR(e.event_date, 'month')   AS event_month_name ,
    c.main_category ,
    coalesce(c.sub_category, 'BRAK') as sub_category ,
    c.sub_sub_category ,
    c.name AS category ,
    es.name as significance,
    case when e.incident_id is NULL then 'NIE' else 'TAK' end as incident
FROM events e
LEFT JOIN categories_em_v c
ON e.category_code = c.category_code
LEFT JOIN event_significance_types es on es.significance_code = e.significance_code;

CREATE VIEW AUTHORITIES AS SELECT 
 e.login as username
, rp.privilege_code as authority
FROM
   employees e
   join employee_role er on e.employee_id = er.employee_id
   join role_privilege rp on rp.role_code = er.role_code;

COMMENT ON TABLE URGENCY_TYPES_PM IS 'S³ownik z typami pilnoœci dla problemów.';

COMMENT ON TABLE URGENCY_TYPES_IM IS 'S³ownik z typami pilnoœci dla incydentów.';

COMMENT ON TABLE SUPPORT_GROUPS IS 'Tabela z grupami wsparcia';

COMMENT ON TABLE STATUSES_RF IS 'S³ownik z mo¿liwymi typami statusów dla zg³oszeñ.';

COMMENT ON TABLE STATUSES_PM IS 'S³ownik z typami statusów dla problemów.';

COMMENT ON TABLE STATUSES_IM IS 'S³ownik z mo¿liowymi statusami dla incydentów.';

COMMENT ON TABLE SOLUTIONS IS 'Tabela zawieraj¹ca rozwi¹zania problemów.  S¹ to zarówno rozwi¹zania tymczasowe oraz rozwi¹zania sta³e.';

COMMENT ON TABLE SOLUTION_TYPES IS 'S³ownik z typami rozwi¹zañ. Mo¿e to byæ rozwi¹zanie sta³e jak i tymczasowe.';

COMMENT ON TABLE SOLUTION_CATEGORIES IS 'S³ownik z typami kategorii rozwi¹zañ.';

COMMENT ON TABLE SIGNALS_TMP IS 'Tabele tymczasowa przechowywuj¹ca dane o sygna³ach, które zostan¹ wygenerowany w zaistnieniu zdarzenia zmiany stanu. Trigger na poziomie wiersza wstawia dane do tej tabeli, natomiast trigger na poziomie tabeli pobiera wiersze z tej tabeli i wstawia do tabeli Signals.';

COMMENT ON TABLE SIGNALS IS 'Zawiera informacje o sygna³ach.';

COMMENT ON TABLE SIGNAL_TYPES IS 'Tabela zawieraj¹ca dane o typach sygna³ów.';

COMMENT ON TABLE SIGNAL_SIGNIFICANCE_TYPES IS 'S³ownik mo¿liwych rang sygna³ów. Przyk³adowe rangi: informacja, ostrze¿enie, b³¹d.';

COMMENT ON TABLE SIGNAL_RECEIVER_TYPES IS 'S³ownik mo¿liwych odbiorców sygna³ów.';

COMMENT ON TABLE SIGNAL_OBJECT_TYPES IS 'Tabele zawieraj¹ce dane o typach obiektów. Przyk³adowe typy to: incydent, problem, zg³oszenie.';

COMMENT ON TABLE SIGNAL_GENERATORS IS 'Zawiera informacje o generatorach sygna³ów.';

COMMENT ON TABLE SIGNAL_ATTRIBUTES IS 'Zawiera informacje o wartoœciach atrybutów sygna³ów.';

COMMENT ON TABLE ROLES IS 'S³ownik z mo¿liwymi rolami dla u¿ytkowników aplikacji.';

COMMENT ON TABLE REQUESTS IS 'Tabela z zg³oszeniami';

COMMENT ON TABLE REQUEST_ATTRIBUTES IS 'Tabela z wartoœciami atrybutów dla zg³oszeñ.';

COMMENT ON TABLE REQUEST_ATTRIBUTE_TYPES IS 'Tabela z typami atrybutów dla danej kateogrii zg³oszenia. Przyk³adowo je¿eli kategoria zg³oszenia jest to instalacja oprogramowania to typami atrybutów mog¹ byæ nazwa aplikacji oraz wersja aplikacji.';

COMMENT ON TABLE PROBLEMS IS 'Tabela z problemami';

COMMENT ON TABLE PRIORITY_TYPES_RF IS 'S³ownik z mo¿liwymi typami priorytetów dla zg³oszeñ.';

COMMENT ON TABLE PRIORITY_TYPES_PM IS 'S³ownik z typami priorytetów dla problemów.';

COMMENT ON TABLE PRIORITY_TYPES_IM IS 'S³ownik z mo¿liwymi priorytetami dla incydentów.';

COMMENT ON TABLE JOBS IS 'S³ownik z mo¿liwymi typami stanowisk.';

COMMENT ON TABLE INCIDENTS_HISTORY IS 'Historia incydentów. Przy ka¿dej zmianie stanu incydentu wstawiany jest wiersz do tej tabeli.';

COMMENT ON TABLE INCIDENTS IS 'Incydenty';

COMMENT ON TABLE INCIDENT_PROBLEM IS 'Tabela asocjacyjna pomiêdzy problemami oraz incydentami.';

COMMENT ON TABLE IMPACT_TYPES_PM IS 'S³ownik z typami wp³ywów dla problemów.';

COMMENT ON TABLE IMPACT_TYPES_IM IS 'S³ownik z typami wp³ywów dla incydentów.';

COMMENT ON TABLE GROUP_MEMBER IS 'Tabela asocjacyjna zawieraj¹ca listê cz³onków danej grupy wsparcia.';

COMMENT ON TABLE EVENTS IS 'Zdarzenia';

COMMENT ON TABLE EVENT_SIGNIFICANCE_TYPES IS 'S³ownik rang dla zdarzeñ. Przyk³adowe rangi to: informacje, ostrze¿enie, b³¹d.';

COMMENT ON TABLE EVENT_PARAMETERS IS 'Lista wartoœci parametrów dla konkretnego zdarzenia.';

COMMENT ON TABLE EVENT_INCIDENT IS 'Tabela asocjacyjna powi¹zuj¹ca zdarzenie z incydentem.';

COMMENT ON TABLE EMPLOYEES IS 'Tabela z pracownikami';

COMMENT ON TABLE EMPLOYEE_ROLE IS 'Tabela asocjacyjna zawieraj¹ca role przypisane dla danego pracownika';

COMMENT ON TABLE DEPARTMENTS IS 'S³ownik z departamentami.';

COMMENT ON TABLE COMMENTS IS 'Tabela z komentarzami';

COMMENT ON TABLE CATEGORIES_RF IS 'S³ownik z mo¿liwymi typami kategorii dla zg³oszeñ.';

COMMENT ON TABLE CATEGORIES_IM IS 'S³ownik z kategoriami incydentów';

COMMENT ON TABLE CATEGORIES_EM IS 'S³ownik kategorii dla zdarzeñ.';

COMMENT ON COLUMN SIGNALS.ERROR_MESSAGE IS 'Komunikat bledu w trakcie wysylania sygnalu';

COMMENT ON COLUMN SIGNAL_GENERATORS.TYPE_CODE IS 'Typ sygna³u';

COMMENT ON COLUMN SIGNAL_GENERATORS.CRITERION IS 'Kryterium, które spe³niaj¹ obiekty';

COMMENT ON COLUMN SIGNAL_GENERATORS.RECEIVER_CODE IS 'Typ odbiorcy';

COMMENT ON COLUMN SIGNAL_GENERATORS.ENABLED IS 'Czy aktywny';

COMMENT ON COLUMN SIGNAL_GENERATORS.FREQUENCY IS 'Czêstotliwoœæ w minutach';

COMMENT ON COLUMN SIGNAL_GENERATORS.LAST_RUN_STATUS IS 'Status ostatnio wykonanej generacji.';

COMMENT ON COLUMN SIGNAL_GENERATORS.LAST_RUN_DATE IS 'Data ostatniej generacji';

COMMENT ON COLUMN SIGNAL_GENERATORS.ERROR_MESSAGE IS 'Komunikat bledu w trakcie generacji sygnalow';

COMMENT ON COLUMN PROBLEMS.IS_KNOWN_ERROR IS 'Czy to znany b³¹d';

COMMENT ON COLUMN PROBLEMS.SUBJECT IS 'Temat problemu';

COMMENT ON COLUMN PROBLEMS.DESCRIPTION IS 'Opis problemu';

COMMENT ON COLUMN PROBLEMS.AUTHOR IS 'Pracownik, która doda³a problem';

COMMENT ON COLUMN PROBLEMS.STAFF_MEMBER IS 'Serwisant do którego jest przypisany problem';

COMMENT ON COLUMN PROBLEMS.GROUP_ID IS 'Grupa wsparcia do której jest przypisany problem';

COMMENT ON COLUMN PRIORITY_TYPES_IM.TARGET_RESOLUTION_TIME IS 'Czas rozwi¹zania incydentu w godzinach.';

COMMENT ON COLUMN JOBS.JOB_CODE IS 'Primary key of jobs table.';

COMMENT ON COLUMN JOBS.JOB_TITLE IS 'A not null column that shows job title, e.g. AD_VP, FI_ACCOUNTANT';

COMMENT ON COLUMN EMPLOYEES.ENABLED IS 'Czy pracownik jest aktywny.';

COMMENT ON COLUMN DEPARTMENTS.DEPARTMENT_ID IS 'Primary key column of departments table.';

COMMENT ON COLUMN DEPARTMENTS.DEPARTMENT_NAME IS 'A not null column that shows name of a department. Administration,
Marketing, Purchasing, Human Resources, Shipping, IT, Executive, Public
Relations, Sales, Finance, and Accounting. ';

COMMENT ON COLUMN DEPARTMENTS.MANAGER_ID IS 'Manager_id of a department. Foreign key to employee_id column of employees table. The manager_id column of the employee table references this column.';

COMMENT ON COLUMN COMMENTS.TEXT IS 'Treœæ komentarza';

COMMENT ON COLUMN COMMENTS.CREATION_DATE IS 'Data dodania komentarza';

COMMENT ON COLUMN COMMENTS.EMPLOYEE_ID IS 'Pracownik, który doda³ komentarz';

COMMENT ON COLUMN CATEGORIES_IM.CATEGORY_CODE IS 'Identyfikator kategorii';

COMMENT ON COLUMN CATEGORIES_IM.NAME IS 'Nazwa kategorii';

COMMENT ON COLUMN CATEGORIES_IM.PARENT_CATEGORY IS 'Identyfikator kategorii nadrzêdnej';

CREATE SEQUENCE SUPPORT_GROUP_ID INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SOLUTION_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SIGNAL_TYPE_ID_SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SIGNAL_PARAM_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SIGNAL_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SIGNAL_GENERATOR_ID_SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE REQ_ATTR_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE PARAMETER_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE INCIDENT_HISTORY_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE HISTORY_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE EVENT_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE EMPLOYEE_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE COMMENT_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE ATTACHMENT_ID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE 
PACKAGE APP 
AS 
  CURRENT_USER_ID NUMBER := 0;
  
  PROCEDURE set_user(user_id NUMBER);
  PROCEDURE set_user_by_login(user_login varchar2);
  FUNCTION get_user RETURN NUMBER;

END APP;
/

CREATE PACKAGE BODY APP AS



  PROCEDURE set_user(user_id NUMBER) AS
  BEGIN
    CURRENT_USER_ID := user_id;
  END set_user;

  FUNCTION get_user RETURN NUMBER AS
  BEGIN
    RETURN CURRENT_USER_ID;
  END get_user;

  PROCEDURE set_user_by_login(user_login varchar2) AS
  BEGIN
    select employee_id into CURRENT_USER_ID from employees where login = user_login;
  END set_user_by_login;

END APP;
/

CREATE PROCEDURE ADD_SIGNAL 
(
  type_code_v IN VARCHAR2  
, employee_id_v IN NUMBER  
, object_id_v IN NUMBER  
) AS
    object_code_v char;
    view_name_v varchar2(30);
    signal_id_v number;
    ir incidents_v%rowtype;
    pr problems_v%rowtype;
BEGIN
    select st.object_code, ot.view_name into object_code_v, view_name_v
    from signal_types st join signal_object_types ot on ot.object_code = st.object_code
    where st.type_code = type_code_v;
    
    insert into signals(SIGNAL_ID, CREATION_DATE,IS_SENT,EMPLOYEE_ID,TYPE_CODE,OBJECT_ID)
    values(signal_id_seq.nextval + 10000000 , sysdate, 'F', employee_id_v, type_code_v, object_id_v)
    returning signal_id
    INTO signal_id_v;
    

    IF object_code_v = 'I' THEN
        select * into ir from incidents_v where incident_id = object_id_v;
        
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISTA', ir.STATUS);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IPRI', ir.PRIORITY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSm', ir.RESOLUTION_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSd', ir.RESOLUTION_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSM', ir.RESOLUTION_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSY', ir.RESOLUTION_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IRSD', ir.RESOLUTION_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLm', ir.CLOSURE_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLd', ir.CLOSURE_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLM', ir.CLOSURE_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLY', ir.CLOSURE_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICLD', ir.CLOSURE_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICTE', ir.CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICT3', ir.SUB_SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICT2', ir.SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ICT1', ir.MAIN_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8m', ir.CREATION_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8Q', ir.CREATION_QUARTER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8M', ir.CREATION_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8Y', ir.CREATION_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8d', ir.CREATION_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IC8D', ir.CREATION_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISUB', ir.SUBJECT);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'IID ', ir.INCIDENT_ID);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISG ', ir.SUPPORT_GROUP);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISM ', ir.STAFF_MEMBER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'ISRC', ir.SOURCE);
    
    ELSIF object_code_v = 'P' THEN
        select * into pr from problems_v where problem_id = object_id_v;
        
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSG ', pr.SUPPORT_GROUP);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSM ', pr.STAFF_MEMBER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSTA', pr.STATUS);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PPRI', pr.PRIORITY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLm', pr.CLOSURE_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLd', pr.CLOSURE_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLM', pr.CLOSURE_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLY', pr.CLOSURE_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCLD', pr.CLOSURE_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT0', pr.CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT3', pr.SUB_SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT2', pr.SUB_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PCT1', pr.MAIN_CATEGORY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8m', pr.CREATION_MONTH_NAME);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8d', pr.CREATION_DAY);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8M', pr.CREATION_MONTH);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8Q', pr.CREATION_QUARTER);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8Y', pr.CREATION_YEAR);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PC8D', pr.CREATION_DATE);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PSUB', pr.SUBJECT);
        insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval + 10000000,signal_id_v,'PID ', pr.PROBLEM_ID);
    END IF;
/*

select
--ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE
    'insert into signal_attributes(ATTRIBUTE_ID,SIGNAL_ID,ATTRIBUTE_CODE,ATTRIBUTE_VALUE) values( SIGNAL_PARAM_ID_SEQ.nextval,signal_id_v,''' || soat.attribute_code || ''', r.' || soat.attribute_name || ');'
from
    user_tab_cols utc
    join signal_object_types sot on upper(utc.table_name) = upper(sot.view_name)
    join signal_object_attribute_types soat on soat.object_code = sot.object_code and upper(soat.attribute_name) = upper(utc.column_name)
where table_name = 'INCIDENTS_V'

*/

END ADD_SIGNAL;
/

CREATE TRIGGER INCIDENT_SIGNALS_TRG2 AFTER INSERT OR UPDATE ON INCIDENTS 
BEGIN
  FOR s IN (SELECT * FROM SIGNALS_TMP) LOOP
    ADD_SIGNAL(s.type_code, s.employee_id, s.object_id);
  END LOOP;
END;
/

CREATE TRIGGER INCIDENT_SIGNALS_TRG BEFORE INSERT OR UPDATE ON INCIDENTS 
FOR EACH ROW 
BEGIN
  IF :old.STATUS_CODE <> :new.STATUS_CODE THEN
    --powiadomienie autora o zmianie statusu
    insert into signals_tmp(type_code, employee_id, object_id) values(1, :new.AUTHOR, :new.INCIDENT_ID);
  END IF;
  
  IF coalesce(:old.STAFF_MEMBER,-1) <> coalesce(:new.STAFF_MEMBER,-1) THEN
    IF :old.STAFF_MEMBER is not NULL THEN
       --powiadomienie serwisanta o odpisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(11, :old.STAFF_MEMBER, :new.INCIDENT_ID);
    END IF;
    IF :new.STAFF_MEMBER is not NULL THEN
        --powiadomienie serwisanta o przypisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(10, :new.STAFF_MEMBER, :new.INCIDENT_ID);
    END IF;
  END IF;
  
  IF coalesce(:old.GROUP_ID,-1) <> coalesce(:new.GROUP_ID,-1) THEN
    IF :old.GROUP_ID is not NULL THEN    
       --powiadomienie menedzera grupy o odpisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(13, (select manager_id from support_groups where group_id = :old.GROUP_ID), :new.INCIDENT_ID);
    END IF;
    IF :new.GROUP_ID is not NULL THEN
        --powiadomienie menedzera grupy o przypisaniu incydentu
       insert into signals_tmp(type_code, employee_id, object_id) values(12, (select manager_id from support_groups where group_id = :new.GROUP_ID), :new.INCIDENT_ID);
    END IF;
  END IF;
  
END;
/

CREATE TRIGGER INCIDENT_HISTORY_TRG AFTER INSERT OR UPDATE ON INCIDENTS 
FOR EACH ROW
DECLARE
    history_id_v number;
    employee_id_v number;
BEGIN
  
  
  select HISTORY_ID_SEQ.nextval, :new.LAST_EDIT_BY into history_id_v, employee_id_v from dual;
  
  insert into incidents_history(
    HISTORY_ID
    ,CHANGE_DATE
    ,EMPLOYEE_ID
    ,INCIDENT_ID
    ,IMPACT_CODE
    ,URGENCY_CODE
    ,STATUS_CODE
    ,REVIEW
    ,PRIORITY_CODE
    ,CATEGORY_CODE
    ,SUBJECT
    ,DESCRIPTION
    ,STAFF_MEMBER
    ,RESOLUTION
    ,SOURCE_CODE
    ,RESOLUTION_DATE
    ,GROUP_ID
    ,TARGET_RESOLUTION_DATE
    ,SERVICE_ID
  )
  values(
    history_id_v
    , sysdate
    , employee_id_v
    , :new.INCIDENT_ID
    , :new.IMPACT_CODE
    , :new.URGENCY_CODE
    , :new.STATUS_CODE
    , :new.REVIEW
    , :new.PRIORITY_CODE
    , :new.CATEGORY_CODE
    , :new.SUBJECT
    , :new.DESCRIPTION
    , :new.STAFF_MEMBER
    , :new.RESOLUTION
    , :new.SOURCE_CODE
    , :new.RESOLUTION_DATE
    , :new.GROUP_ID
    , :new.TARGET_RESOLUTION_DATE
    , :new.SERVICE_ID
  );
  
END;
/