INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (1, 'Niski', 'N', 1000);
INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (2, 'Œredni', 'N', 2000);
INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (3, 'Wysoki', 'N', 3000);
INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (4, 'Pilny', 'Y', 4000);

INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (1, 'Ma³y', 1000);
INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (2, 'Œredni', 2000);
INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (3, 'Du¿y', 3000);
INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (4, 'Katastrofalny', 4000);

INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (1, 'wykonano', 1000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (2, 'wycofano', 2000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (3, 'niezatwierdzono', 3000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (4, 'odroczono', 4000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (10, 'niepoprawny', 10000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (11, 'duplikat', 11000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (12, 'niewa¿ny', 12000);


INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1, 'Pracownicze', 'N', NULL);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (2, 'Sprzêtowe', 'N', NULL);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (3, 'Awarie', 'N', 2);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (4, 'Wymiana', 'N', 2);