INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (1, 'Niski', 'N', 1000);
INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (2, 'Œredni', 'N', 2000);
INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (3, 'Wysoki', 'N', 3000);
INSERT INTO RFC_PRIORITIES(PRIORITY_ID, NAME, URGENT, "ORDER") VALUES (4, 'Pilny', 'Y', 4000);

INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (1, 'Ma³y', 1000);
INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (2, 'Œredni', 2000);
INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (3, 'Du¿y', 3000);
INSERT INTO RFC_IMPACTS(IMPACT_ID, NAME, "ORDER") VALUES (4, 'Katastrofalny', 4000);

INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (1, 'wykonano', 1000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (2, 'wycofano', 2000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (3, 'niezatwierdzono', 3000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (4, 'odroczono', 4000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (10, 'niepoprawny', 10000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (11, 'duplikat', 11000);
INSERT INTO RFC_RESOLUTIONS(RESOLUTION_ID, NAME, "ORDER") VALUES (12, 'niewa¿ny', 12000);


INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1000, 'Us³ugi', 'Y', NULL);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1100, 'Hosting kolokacyjny', 'N', 1000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1200, 'Hosting dedykowany', 'N', 1000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1300, 'Wirtualny hosting dedykowany', 'N', 1000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1400, 'Hosting wspó³dzielony', 'N', 1000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1500, 'Wspó³dzielony hosting stron internetowych', 'N', 1000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1600, 'Darmowy hosting stron internetowych', 'N', 1000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (1700, 'Hosting poœredni', 'N', 1000);

INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (2000, 'Infrastruktura', 'Y', NULL);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (2100, 'Serwerownia 1', 'N', 2000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (2200, 'Serwerownia 2', 'N', 2000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (2300, 'Serwerownia 3', 'N', 2000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (2400, 'Serwerownia 4', 'N', 2000);


INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (3000, 'Zg³aszane przez klienta', 'Y', NULL);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (3100, 'Zmiana poziomu us³ugi', 'N', 3000);
INSERT INTO RFC_CATEGORIES(CATEGORY_ID, NAME, ABSTRACT, PARENT_CATEGORY_ID) VALUES (3200, 'Instalacja dodatkowego oprogramowania', 'N', 3000);
