insert into jobs(job_code, job_title) values('AD_PRES', 'President');
insert into jobs(job_code, job_title) values('AD_VP', 'Administration Vice President');
insert into jobs(job_code, job_title) values('AD_ASST', 'Administration Assistant');
insert into jobs(job_code, job_title) values('FI_MGR', 'Finance Manager');
insert into jobs(job_code, job_title) values('FI_ACCOUNT', 'Accountant');
insert into jobs(job_code, job_title) values('AC_MGR', 'Accounting Manager');
insert into jobs(job_code, job_title) values('AC_ACCOUNT', 'Public Accountant');
insert into jobs(job_code, job_title) values('SA_MAN', 'Sales Manager');
insert into jobs(job_code, job_title) values('SA_REP', 'Sales Representative');
insert into jobs(job_code, job_title) values('PU_MAN', 'Purchasing Manager');
insert into jobs(job_code, job_title) values('PU_CLERK', 'Purchasing Clerk');
insert into jobs(job_code, job_title) values('ST_MAN', 'Stock Manager');
insert into jobs(job_code, job_title) values('ST_CLERK', 'Stock Clerk');
insert into jobs(job_code, job_title) values('SH_CLERK', 'Shipping Clerk');
insert into jobs(job_code, job_title) values('IT_PROG', 'Programmer');
insert into jobs(job_code, job_title) values('MK_MAN', 'Marketing Manager');
insert into jobs(job_code, job_title) values('MK_REP', 'Marketing Representative');
insert into jobs(job_code, job_title) values('HR_REP', 'Human Resources Representative');
insert into jobs(job_code, job_title) values('PR_REP', 'Public Relations Representative');