CREATE OR REPLACE TRIGGER INCIDENT_SIGNALS_TRG2 
AFTER INSERT OR UPDATE ON INCIDENTS 
BEGIN
  FOR s IN (SELECT * FROM SIGNALS_TMP) LOOP
    ADD_SIGNAL(s.type_code, s.employee_id, s.object_id);
  END LOOP;
END;
/
