CREATE OR REPLACE TRIGGER c2_autoinsert_incidents
    AFTER INSERT ON incidents
    REFERENCING NEW AS incident
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID, LABEL)
        VALUES (C2_ENTITIES_SEQ.currval, 'INCYDENT #' || to_char(:incident.INCIDENT_ID));

    INSERT INTO C2_ITEMS_INCIDENT (ITEM_ID, INCIDENT_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :incident.INCIDENT_ID);
END;
/
