CREATE OR REPLACE TRIGGER c2_autoinsert_services
    AFTER INSERT ON services
    REFERENCING NEW AS service
    FOR EACH ROW
BEGIN
    INSERT INTO C2_ENTITIES (ENTITY_ID, VERSION)
        VALUES (C2_ENTITIES_SEQ.nextval, 0);
		
	INSERT INTO C2_ITEMS (ITEM_ID, LABEL)
        VALUES (C2_ENTITIES_SEQ.currval, 'USŁUGA #' || to_char(:service.SERVICE_ID));

    INSERT INTO C2_ITEMS_SERVICE (ITEM_ID, SERVICE_ID)
        VALUES (C2_ENTITIES_SEQ.currval, :service.SERVICE_ID);
END;
/
